version: '3.7'
services:
  shiny:
    build:
      context: ./docker/shiny
      target: prod
    image: geiser/tertiary-study-of-gamification_shiny
    container_name: tertiary-study-of-gamification_shiny
    ports:
      - "3939:3838"
    volumes:
      - '.:/srv/shiny-server/tertiary-study-of-gamification'
      - './shiny_logs:/var/log/shiny-server'
  dev:
    image: geiser/r-studio:latest
    container_name: tertiary-study-of-gamification_dev
    ports:
      - "8787:8787"
    volumes:
      - '.:/home/gcc'
