<?xml version="1.0" encoding="UTF-8"?>
<map version="1.1.0">
  <node TEXT="Without classification">
    <node LINK="http://zotero.org/groups/2366342/items/CWIJWKDI/file?page=1" TEXT="Key: 7TDZ6AH3 &lt;br/&gt;&lt;br/&gt;Context: building services engineering education at university level (field: education, discipline: building services engineering, level degree: university) (by the authors); &lt;br/&gt;&lt;br/&gt;Title: An overview of game-based learning in building services engineering education"/>
    <node LINK="http://zotero.org/groups/2366342/items/2GCQL6NK/file?page=1" TEXT="Key: U6XEEV4R &lt;br/&gt;&lt;br/&gt;Context: Gamification (by the authors); &lt;br/&gt;&lt;br/&gt;Title: A Wide View on Gamification"/>
    <node LINK="http://zotero.org/groups/2366342/items/83UPKQA9/file?page=2" TEXT="Key: U9NNBC8C &lt;br/&gt;&lt;br/&gt;Context: primary level learners (6 - 12 years old) (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Game-play: Effects of online gamified and game-based learning on dispositions, abilities and behaviours of primary learners"/>
    <node LINK="http://zotero.org/groups/2366342/items/DFEK6V3A/file?page=2" TEXT="Key: Z48MVVX8 &lt;br/&gt;&lt;br/&gt;Context: software enginnering education (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification in software engineering education: A systematic mapping"/>
    <node LINK="http://zotero.org/groups/2366342/items/PTATWLKY/file?page=1" TEXT="Key: DU6Q5ZT4 &lt;br/&gt;&lt;br/&gt;Context: personalization in gamified learning experience (by the authors); &lt;br/&gt;&lt;br/&gt;Title: A Review on Adopting Personalized Gamified Experience in the Learning Context"/>
    <node LINK="http://zotero.org/groups/2366342/items/GJLS77LT/file?page=1" TEXT="Key: KCH5UA2F &lt;br/&gt;&lt;br/&gt;Context: online collaborative learning for programming courses (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification in online collaborative learning for programming courses: A literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/RYA447QD/file?page=1" TEXT="Key: T8WEGLL6 &lt;br/&gt;&lt;br/&gt;Context: Gamification design framework  (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification design frameworks: A systematic mapping study"/>
    <node LINK="http://zotero.org/groups/2366342/items/EGSYEKAE/file?page=1" TEXT="Key: PWFJQCSD &lt;br/&gt;&lt;br/&gt;Context: Gamification and serious games (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification and serious games: A literature meta-analysis and integrative model"/>
    <node LINK="http://zotero.org/groups/2366342/items/W5EWFPQK/file?page=1" TEXT="Key: WYJGAGR5 &lt;br/&gt;&lt;br/&gt;Context: education (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification in education: A systematic mapping study"/>
    <node LINK="http://zotero.org/groups/2366342/items/LGIJHJ49/file?page=1" TEXT="Key: EEXF9MBB &lt;br/&gt;&lt;br/&gt;Context: health and well-being (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification for health and wellbeing: A systematic review of the literature"/>
    <node LINK="http://zotero.org/groups/2366342/items/68Z32TLH/file?page=1" TEXT="Key: TJHX8G2L &lt;br/&gt;&lt;br/&gt;Context: education/training (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification and education: A literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/3VQR92B5/file?page=2" TEXT="Key: DATSPTCJ &lt;br/&gt;&lt;br/&gt;Context: Adaptive gamification (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Towards adaptive gamification: A synthesis of current developments"/>
    <node LINK="http://zotero.org/groups/2366342/items/EH6UY6U2/file?page=1" TEXT="Key: KRXCF7LK &lt;br/&gt;&lt;br/&gt;Context: gamification research (by the authors); &lt;br/&gt;&lt;br/&gt;Title: A systematic review of gamification research: In pursuit of homo ludens"/>
    <node LINK="http://zotero.org/groups/2366342/items/PDB6L8NP/file?page=1" TEXT="Key: D6JRWRYL &lt;br/&gt;&lt;br/&gt;Context: Information Systems (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification - A new phenomenon in information systems research?"/>
    <node LINK="http://zotero.org/groups/2366342/items/YA6SB28S/file?page=1" TEXT="Key: P99JDRWW &lt;br/&gt;&lt;br/&gt;Context: framework for gamification (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification-A novel phenomenon or a new wrapping for existing concepts?"/>
    <node LINK="http://zotero.org/groups/2366342/items/42Q3VTRN/file?page=1" TEXT="Key: QZ6TGPTD &lt;br/&gt;&lt;br/&gt;Context: cognitive training and the memory improvement of elderlies (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Accessibility and Gamification Applied to Cognitive Training and Memory Improvement"/>
    <node LINK="http://zotero.org/groups/2366342/items/EQY43MLP/file?page=1" TEXT="Key: U4WPI2ZX &lt;br/&gt;&lt;br/&gt;Context: Gamification in Software Testing (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification in software testing: A characterization study"/>
    <node LINK="http://zotero.org/groups/2366342/items/FSEVDEN3/file?page=1" TEXT="Key: ECX2HIP3 &lt;br/&gt;&lt;br/&gt;Context: gamification (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Does gamification work? - A literature review of empirical studies on gamification"/>
    <node LINK="http://zotero.org/groups/2366342/items/CCB3FSL7/file?page=1" TEXT="Key: DQ32WLL9 &lt;br/&gt;&lt;br/&gt;Context: Gamification Analytics (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Tools for gamification analytics: A survey"/>
    <node LINK="http://zotero.org/groups/2366342/items/4FDSTPP7/file?page=1" TEXT="Key: 4CZIYDAR &lt;br/&gt;&lt;br/&gt;Context: the use of gamification for the promotion of behavioral change (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification mechanics for behavioral change: A systematic review and proposed taxonomy"/>
    <node LINK="http://zotero.org/groups/2366342/items/G8TH79GQ/file?page=1" TEXT="Key: EH5CURBS &lt;br/&gt;&lt;br/&gt;Context: gamification and serious games in domestic energy consumption domestic energy consumption (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification and serious games within the domain of domestic energy consumption: A systematic review"/>
    <node LINK="http://zotero.org/groups/2366342/items/UURKLF8G/file?page=1" TEXT="Key: R8VGHPLF &lt;br/&gt;&lt;br/&gt;Context: the evaluation of gamification in educational environments (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Does gamification matter?: A systematic mapping about the evaluation of gamification in educational environments"/>
    <node LINK="http://zotero.org/groups/2366342/items/R76JUB22/file?page=1" TEXT="Key: BGZD5LHM &lt;br/&gt;&lt;br/&gt;Context: Digital game-based learning and gamification in the context of enginnering education (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Systematic literature review: An exploration of gamification in the context of engineering education"/>
    <node LINK="http://zotero.org/groups/2366342/items/3PIVJ6GK/file?page=1" TEXT="Key: 8ZS7Y34V &lt;br/&gt;&lt;br/&gt;Context: software engineering (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification in software engineering - A systematic mapping"/>
    <node LINK="http://zotero.org/groups/2366342/items/6QGS7ZD7/file?page=1" TEXT="Key: 2SK6I79L &lt;br/&gt;&lt;br/&gt;Context: Gamification (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification in theory and action: A survey"/>
    <node LINK="http://zotero.org/groups/2366342/items/6RBHK2DA/file?page=1" TEXT="Key: Z4TEK8UD &lt;br/&gt;&lt;br/&gt;Context: game-related methods for software engineering education (by the authors); &lt;br/&gt;&lt;br/&gt;Title: A systematic mapping study on game-related methods for software engineering education"/>
    <node LINK="http://zotero.org/groups/2366342/items/BQ4NEBUZ/file?page=2" TEXT="Key: T7YP4UMR &lt;br/&gt;&lt;br/&gt;Context: gamification in Open and Distance Learning (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification in Open and Distance Learning: A Systematic Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/4EZHHB7U" TEXT="Key: 4EZHHB7U &lt;br/&gt;&lt;br/&gt;Context: mobile healthcare (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification for mHealth - A review of playful mobile healthcare">
      <node LINK="/file?page=NA"/>
      <node LINK="/file?page=NA"/>
    </node>
    <node LINK="http://zotero.org/groups/2366342/items/AK78SR4D/file?page=1" TEXT="Key: SI4M7V5U &lt;br/&gt;&lt;br/&gt;Context: software user engagement (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification Solutions to Enhance Software User Engagement—A Systematic Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/SY5JIJRU/file?page=1" TEXT="Key: LV9728GC &lt;br/&gt;&lt;br/&gt;Context: Education (by the authors); &lt;br/&gt;&lt;br/&gt;Title: A systematic mapping on gamification applied to education"/>
    <node LINK="http://zotero.org/groups/2366342/items/XXUDEFYP/file?page=1" TEXT="Key: UIG5J5VN &lt;br/&gt;&lt;br/&gt;Context: education (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamifying education: what is known, what is believed and what remains uncertain: a critical review"/>
    <node LINK="http://zotero.org/groups/2366342/items/F2EDJU4Y/file?page=1" TEXT="Key: E6MRNT62 &lt;br/&gt;&lt;br/&gt;Context: health promotion (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification for health promotion: systematic review of behaviour change techniques in smartphone apps"/>
    <node LINK="http://zotero.org/groups/2366342/items/MEE3FCH3/file?page=1" TEXT="Key: GRZ9DTI4 &lt;br/&gt;&lt;br/&gt;Context: gamification research (by the authors); &lt;br/&gt;&lt;br/&gt;Title: The rise of motivational information systems: A review of gamification research"/>
    <node LINK="http://zotero.org/groups/2366342/items/FJ7VYX6E/file?page=1" TEXT="Key: RCH96TH6 &lt;br/&gt;&lt;br/&gt;Context: Reward Systems Implemented in Gamification Interventions (by the authors); &lt;br/&gt;&lt;br/&gt;Title: What's the Point?: A Review of Reward Systems Implemented in Gamification Interventions"/>
    <node LINK="http://zotero.org/groups/2366342/items/7P67KPYE/file?page=1" TEXT="Key: RI98ZX22 &lt;br/&gt;&lt;br/&gt;Context: online programs &#10;&#10;  (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Does gamification increase engagement with online programs? A systematic review"/>
    <node LINK="http://zotero.org/groups/2366342/items/GZPP6FJE/file?page=1" TEXT="Key: S6PYB3SX &lt;br/&gt;&lt;br/&gt;Context: Cognitive tasks (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification of Cognitive Assessment and Cognitive Training: A Systematic Review of Applications and Efficacy"/>
    <node LINK="http://zotero.org/groups/2366342/items/8P9TYZAQ/file?page=2" TEXT="Key: JXAJL6D8 &lt;br/&gt;&lt;br/&gt;Context: education and learning (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification of education and learning: A review of empirical literature"/>
    <node LINK="http://zotero.org/groups/2366342/items/H4T9NS5C/file?page=1" TEXT="Key: 5TF845KW &lt;br/&gt;&lt;br/&gt;Context: education (by the authors); &lt;br/&gt;&lt;br/&gt;Title: The use of gamification in education: a bibliometric and text mining analysis"/>
    <node LINK="http://zotero.org/groups/2366342/items/5YLXK7VY/file?page=1" TEXT="Key: B4R2NGS5 &lt;br/&gt;&lt;br/&gt;Context: gamification design frameworks (by the authors); &lt;br/&gt;&lt;br/&gt;Title: A Literature Review of Gamification Design Frameworks"/>
    <node LINK="http://zotero.org/groups/2366342/items/8MGXGRGM/file?page=1" TEXT="Key: NKQHGXWL &lt;br/&gt;&lt;br/&gt;Context: gamification design frameworks (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification: a systematic review of design frameworks"/>
    <node LINK="http://zotero.org/groups/2366342/items/F7TWMF26/file?page=1" TEXT="Key: YNX86BJG &lt;br/&gt;&lt;br/&gt;Context: crowdsourcing (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification in crowdsourcing: A review"/>
    <node LINK="http://zotero.org/groups/2366342/items/DJLTYYUF/file?page=1" TEXT="Key: P2HVLMMV &lt;br/&gt;&lt;br/&gt;Context: crowdsourcing (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamified crowdsourcing: Conceptualization, literature review, and future agenda"/>
    <node LINK="http://zotero.org/groups/2366342/items/E8WSFLSN/file?page=1" TEXT="Key: WA7YFUPZ &lt;br/&gt;&lt;br/&gt;Context: gamification research (by the authors); &lt;br/&gt;&lt;br/&gt;Title: How multidisciplinary is gamification research? Results from a scoping review"/>
    <node LINK="http://zotero.org/groups/2366342/items/RQLWQJVM/file?page=1" TEXT="Key: ETKZWGUM &lt;br/&gt;&lt;br/&gt;Context: e-Health &#10;&#10;health and wellness contexts, specifically to chronic disease rehabilitation, physical activity and mental health.   (by the authors); &lt;br/&gt;&lt;br/&gt;Title: A systematic review of gamification in e-Health"/>
    <node LINK="http://zotero.org/groups/2366342/items/PQ5QBBU6/file?page=1" TEXT="Key: 3IU8N247 &lt;br/&gt;&lt;br/&gt;Context: self-management of diabetes (by the authors); &lt;br/&gt;&lt;br/&gt;Title: The Use of Videogames, Gamification, and Virtual Environments in the Self-Management of Diabetes: A Systematic Review of Evidence"/>
    <node LINK="http://zotero.org/groups/2366342/items/RX579NY3/file?page=2" TEXT="Key: WPQ7UQ39 &lt;br/&gt;&lt;br/&gt;Context: information systems (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamifying information systems - A synthesis of gamification mechanics and dynamics"/>
    <node LINK="http://zotero.org/groups/2366342/items/ZFNMEM6V/file?page=1" TEXT="Key: 5WSN7HXA &lt;br/&gt;&lt;br/&gt;Context: Web-based interventions for common mental disorders (CMDs) and well-being (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification and Adherence to Web-Based Mental Health Interventions: A Systematic Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/LYU6XR5U/file?page=1" TEXT="Key: MSXNJE96 &lt;br/&gt;&lt;br/&gt;Context: Gamification strategies for Mobile Device (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification strategies for mobile device applications: A systematic review"/>
    <node LINK="http://zotero.org/groups/2366342/items/AY39YFUS/file?page=2" TEXT="Key: ARK2VNHT &lt;br/&gt;&lt;br/&gt;Context: game-based learning (by the authors); &lt;br/&gt;&lt;br/&gt;Title: A review of research questions, theories and methodologies for game- based learning"/>
    <node LINK="http://zotero.org/groups/2366342/items/5DKWAQSJ/file?page=1" TEXT="Key: UZPSHLXP &lt;br/&gt;&lt;br/&gt;Context: Application of gamification in Requirements Engineering (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification in requirements engineering: A systematic review"/>
    <node LINK="http://zotero.org/groups/2366342/items/9QP9FGVV/file?page=1" TEXT="Key: 7NS3UMP3 &lt;br/&gt;&lt;br/&gt;Context: gamification models supporting a variety of motivational characteristics to provide engagement solutions for different areas (by the authors); &lt;br/&gt;&lt;br/&gt;Title: A systematic mapping study of gamification models oriented to motivational characteristics"/>
    <node LINK="http://zotero.org/groups/2366342/items/5QCMGSKD/file?page=1" TEXT="Key: J55GXR2E &lt;br/&gt;&lt;br/&gt;Context: Gamification and serious games in depression care (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification and serious games in depression care: A systematic mapping study"/>
    <node LINK="http://zotero.org/groups/2366342/items/RCP7K3FB/file?page=1" TEXT="Key: R3RHLTP9 &lt;br/&gt;&lt;br/&gt;Context: education (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification for Education: Review of Current Publications"/>
    <node LINK="http://zotero.org/groups/2366342/items/89V5FFW7/file?page=1" TEXT="Key: PUIEIUE2 &lt;br/&gt;&lt;br/&gt;Context: education (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Using gamification in education: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/ZEUQGR9V/file?page=1" TEXT="Key: K96HQITW &lt;br/&gt;&lt;br/&gt;Context: Educational Functions and Design of Badge Systems &#10;&#10;  (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Educational functions and design of badge systems: A conceptual literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/KPSZJH37/file?page=1" TEXT="Key: NV2RJ7PF &lt;br/&gt;&lt;br/&gt;Context: gamification to the work domain (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification in the workplace: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/BEGGW57J/file?page=1" TEXT="Key: J46W4KVE &lt;br/&gt;&lt;br/&gt;Context: gamification in healthcare (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Health Care Gamification: A Study of Game Mechanics and Elements"/>
    <node LINK="http://zotero.org/groups/2366342/items/YWZLLIUS/file?page=1" TEXT="Key: SL5PHI9K &lt;br/&gt;&lt;br/&gt;Context: Serious Gaming and Gamification Education in Health Professions (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Serious gaming and gamification education in health professions: systematic review"/>
    <node LINK="http://zotero.org/groups/2366342/items/5F36YA7T/file?page=1" TEXT="Key: FF5ZEASV &lt;br/&gt;&lt;br/&gt;Context: mechanics, psychological mediators and desired outcomes (by the authors); &lt;br/&gt;&lt;br/&gt;Title: An interdisciplinary perspective on gamification: Mechanics, psychological mediators and outcomes"/>
    <node LINK="http://zotero.org/groups/2366342/items/PF9N57QW/file?page=2" TEXT="Key: V4KJP7K7 &lt;br/&gt;&lt;br/&gt;Context: organization training (by the authors); &lt;br/&gt;&lt;br/&gt;Title: A systematic literature review on organizational training using game-based learning"/>
    <node LINK="http://zotero.org/groups/2366342/items/WAV7W72K/file?page=NA" TEXT="Key: 67ICM9VZ &lt;br/&gt;&lt;br/&gt;Context: gamification (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Publication trends in gamification: A systematic mapping study"/>
    <node LINK="http://zotero.org/groups/2366342/items/B5JPB9LV/file?page=1" TEXT="Key: ECEURTHW &lt;br/&gt;&lt;br/&gt;Context: gamification in surveys (by the authors); &lt;br/&gt;&lt;br/&gt;Title: A Review of Issues in Gamified Surveys"/>
    <node LINK="http://zotero.org/groups/2366342/items/YABDS4GN/file?page=1" TEXT="Key: T87XI89T &lt;br/&gt;&lt;br/&gt;Context: Massive Open Online Course (MOOC) (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification in MOOCs: A review of the state of the art"/>
    <node LINK="http://zotero.org/groups/2366342/items/KY3DI2Q4/file?page=2" TEXT="Key: CIBCVT7A &lt;br/&gt;&lt;br/&gt;Context: the use of Gamification on Higher Education Institutions (HEIs), particularly on Management undergraduate classes  (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification in a Management Education: Systematic Literature Review and a Proposal of a Conceptual Research Model"/>
    <node LINK="http://zotero.org/groups/2366342/items/3KK9S6TH/file?page=1" TEXT="Key: H2YIIQUG &lt;br/&gt;&lt;br/&gt;Context: game-based approaches to support education about diseases transmitted by Aedes mosquitoes (by the authors); &lt;br/&gt;&lt;br/&gt;Title: A Systematic Mapping of Game-Based Methods to Tackle a Public Health Problem"/>
    <node LINK="http://zotero.org/groups/2366342/items/RWNJBNWN/file?page=1" TEXT="Key: PWY2VLLS &lt;br/&gt;&lt;br/&gt;Context: elements of gamification for learning in higher education (by the authors); &lt;br/&gt;&lt;br/&gt;Title: The elements of gamification learning in higher education: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/3F4TY7AA/file?page=1" TEXT="Key: L2SMT2Y5 &lt;br/&gt;&lt;br/&gt;Context: software project management areas (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification for improving software project management processes: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/X53YHVAX/file?page=1" TEXT="Key: G5488BUN &lt;br/&gt;&lt;br/&gt;Context: gamification for waste management and gamification for schoolchildren (by the authors); &lt;br/&gt;&lt;br/&gt;Title: A review of the applicability of gamification and game-based learning to improve household-level waste management practices among schoolchildren"/>
    <node LINK="http://zotero.org/groups/2366342/items/SGTGM7SQ/file?page=1" TEXT="Key: M3FPSZRG &lt;br/&gt;&lt;br/&gt;Context: gamification elements in teaching and learning &#10;&#10;  (by the authors); &lt;br/&gt;&lt;br/&gt;Title: An analysis of gamification elements in online learning to enhance learning engagement"/>
    <node LINK="http://zotero.org/groups/2366342/items/MGZ6GW94/file?page=1" TEXT="Key: XJA5EYK7 &lt;br/&gt;&lt;br/&gt;Context: Serious games and gamification to engage consumers in pro-environmental behaviours for energy efficiency (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gaming for Earth: Serious games and gamification to engage consumers in pro-environmental behaviours for energy efficiency"/>
    <node LINK="http://zotero.org/groups/2366342/items/NB66S9QS/file?page=1" TEXT="Key: ZJHE67L6 &lt;br/&gt;&lt;br/&gt;Context: Software Business Landscapes (by the authors); &lt;br/&gt;&lt;br/&gt;Title: A systematic investigation into the use of game elements in the context of software business landscapes: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/2929SPWN/file?page=1" TEXT="Key: HF93EUY8 &lt;br/&gt;&lt;br/&gt;Context: gamification in MOOCs (by the authors); &lt;br/&gt;&lt;br/&gt;Title: How gamification is being implemented in MOOCs? A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/W68NI75Q/file?page=1" TEXT="Key: 6HUGE6AZ &lt;br/&gt;&lt;br/&gt;Context: gamification on learning performance (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification and learning performance: A systematic review of the literature"/>
    <node LINK="http://zotero.org/groups/2366342/items/8GV9EAM4/file?page=1" TEXT="Key: NYRPEYLB &lt;br/&gt;&lt;br/&gt;Context: STEM Higher Education (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification in higher education and STEM : a systematic review of literature"/>
    <node LINK="http://zotero.org/groups/2366342/items/W4UVTB7N/file?page=9" TEXT="Key: 2YLQ59FZ &lt;br/&gt;&lt;br/&gt;Context: gamification in IS education (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Systematic review of gamification research in is education: A multi-method approach"/>
    <node LINK="http://zotero.org/groups/2366342/items/5VCZGAB4/file?page=2" TEXT="Key: KYAFM9NF &lt;br/&gt;&lt;br/&gt;Context: Gamification Requirements for Educational Software (by the authors); &lt;br/&gt;&lt;br/&gt;Title: A gamification requirements catalog for educational software: Results from a systematic literature review and a survey with experts"/>
    <node LINK="http://zotero.org/groups/2366342/items/7R6TXZD9" TEXT="Key: 7R6TXZD9 &lt;br/&gt;&lt;br/&gt;Context: online-based learning (by the authors); &lt;br/&gt;&lt;br/&gt;Title: A review of intrinsic motivation elements in gamified online learning">
      <node LINK="http://zotero.org/groups/2366342/items/IPGZ7KH4/file?page=1" TEXT="A review of intrinsic motivation elements in gamified online learning.pdf"/>
      <node LINK="http://zotero.org/groups/2366342/items/YU3A4YPR/file?page=1" TEXT="Saputro et al_2017_A review of intrinsic motivation elements in gamified online learning.pdf"/>
    </node>
    <node LINK="http://zotero.org/groups/2366342/items/5FHYJFR3/file?page=2" TEXT="Key: U7QVQBPN &lt;br/&gt;&lt;br/&gt;Context: Information Systems (by the authors); &lt;br/&gt;&lt;br/&gt;Title: A descriptive literature review and classification framework for Gamification in information systems"/>
    <node LINK="http://zotero.org/groups/2366342/items/AAP5YV7B/file?page=2" TEXT="Key: X38B6A2J &lt;br/&gt;&lt;br/&gt;Context: gamification in information systems (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Is it all about having fun? - Developing a taxonomy to gamify information systems"/>
    <node LINK="http://zotero.org/groups/2366342/items/NY3HCY5C/file?page=3" TEXT="Key: CTWV9HQ7 &lt;br/&gt;&lt;br/&gt;Context: learning (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Developing a comprehensive Engagement framework of gamification for reflective learning"/>
    <node LINK="http://zotero.org/groups/2366342/items/UK48D9L7/file?page=3" TEXT="Key: NK6LBMCR &lt;br/&gt;&lt;br/&gt;Context: game-based learning and gamification in Asia K-12 schools (by the authors); &lt;br/&gt;&lt;br/&gt;Title: A systematic literature review of game-based learning and gamification research in Asia"/>
    <node LINK="http://zotero.org/groups/2366342/items/TGV6N9SZ/file?page=1" TEXT="Key: L2RA2UBF &lt;br/&gt;&lt;br/&gt;Context: game-related approaches in software engineering education (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Games for learning: Bridging game-related education methods to software engineering knowledge areas"/>
    <node LINK="http://zotero.org/groups/2366342/items/RV2UBJ99/file?page=2" TEXT="Key: HK8Z22AQ &lt;br/&gt;&lt;br/&gt;Context: gamified Health Behaviour Change Support Systems (HBCSS) for health promotion (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification applied for health promotion: Does it really foster long-term engagement? A scoping review"/>
    <node LINK="http://zotero.org/groups/2366342/items/FEDIZU3J/file?page=1" TEXT="Key: R3JY98IF &lt;br/&gt;&lt;br/&gt;Context: gamification in higher education &#10;&#10;  (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamified learning in higher education: A systematic review of the literature"/>
    <node LINK="http://zotero.org/groups/2366342/items/8AI5LB5S/file?page=1" TEXT="Key: PFH7CS9C &lt;br/&gt;&lt;br/&gt;Context: education (by the authors); &lt;br/&gt;&lt;br/&gt;Title: The role of gamification in education - a literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/NKEUQSFJ/file?page=1" TEXT="Key: KWFWFYLZ &lt;br/&gt;&lt;br/&gt;Context: In-Home Rehabilitation for Stroke Survivors (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamified In-Home Rehabilitation for Stroke Survivors: Analytical Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/HU7QC9C3/file?page=1" TEXT="Key: FKW6CPKF &lt;br/&gt;&lt;br/&gt;Context: Virtual Learning Environments (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Elements of gamification in virtual learning environments: A systematic review"/>
    <node LINK="http://zotero.org/groups/2366342/items/D4F497R6/file?page=2" TEXT="Key: 9R7PKXA8 &lt;br/&gt;&lt;br/&gt;Context: education (by the authors); &lt;br/&gt;&lt;br/&gt;Title: The dark side of gamification: An overview of negative effects of gamification in education"/>
    <node LINK="http://zotero.org/groups/2366342/items/7HNL8CRV/file?page=1" TEXT="Key: ADVZHZCX &lt;br/&gt;&lt;br/&gt;Context: Gamification Monitoring (by the authors); &lt;br/&gt;&lt;br/&gt;Title: A systematic literature review on the gamification monitoring phase: How SPI standards can contribute to gamification maturity"/>
    <node LINK="http://zotero.org/groups/2366342/items/2EF4HZHZ/file?page=1" TEXT="Key: 8EBQ7DX2 &lt;br/&gt;&lt;br/&gt;Context: Requirement engineering (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Leveraging motivational theories for designing gamification for RE"/>
    <node LINK="http://zotero.org/groups/2366342/items/NEL8VNPT/file?page=1" TEXT="Key: UIBJE3DK &lt;br/&gt;&lt;br/&gt;Context: software quality (by the authors); &lt;br/&gt;&lt;br/&gt;Title: A Systematic Mapping Study on Gamified Software Quality"/>
    <node LINK="http://zotero.org/groups/2366342/items/NZVCHWH8/file?page=2" TEXT="Key: LKHFFTQA &lt;br/&gt;&lt;br/&gt;Context: advertising &#10;&#10;  (by the authors); &lt;br/&gt;&lt;br/&gt;Title: What we know and need to know about the gamification of advertising: A review and synthesis of the advergame studies"/>
    <node LINK="http://zotero.org/groups/2366342/items/S69ERHTA/file?page=1" TEXT="Key: I9T65NFC &lt;br/&gt;&lt;br/&gt;Context: healthcare system (by the authors); &lt;br/&gt;&lt;br/&gt;Title: A survey of gamification for healthcare system"/>
    <node LINK="http://zotero.org/groups/2366342/items/ALSIWPM6/file?page=1" TEXT="Key: T5YC9UJZ &lt;br/&gt;&lt;br/&gt;Context: cognitive bias modification interventions (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamified Cognitive Bias Modification Interventions for Psychiatric Disorders: Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/ZDP4KPH8/file?page=1" TEXT="Key: W5MLYYKE &lt;br/&gt;&lt;br/&gt;Context: production and logistics operations in organizational contexts (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification of production and logistics operations: Status quo and future directions"/>
  </node>
</map>
