<?xml version="1.0" encoding="UTF-8"?>
<map version="1.1.0">
  <node TEXT="Without classification">
    <node LINK="http://zotero.org/groups/2366342/items/EAWY3579/file?page=1" TEXT="Key: JNRX3YE3 &lt;br/&gt;&lt;br/&gt;Context: e-government (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification in e-Govemment: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/MV3ESRRI/file?page=1" TEXT="Key: 7M2RXEDT &lt;br/&gt;&lt;br/&gt;Context: Problem-based learning (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Problem based learning using gamification: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/34H9ZFI6/file?page=1" TEXT="Key: SW5VNQKY &lt;br/&gt;&lt;br/&gt;Context: education domain for e-learning platforms (by the authors); &lt;br/&gt;&lt;br/&gt;Title: A Gamification Model for E-Learning Platforms"/>
    <node LINK="http://zotero.org/groups/2366342/items/ZRJZK6MC/file?page=1" TEXT="Key: DMU5DZ9P &lt;br/&gt;&lt;br/&gt;Context: Learning Programming Fundamental (by the authors); &lt;br/&gt;&lt;br/&gt;Title: A Review of Gamification for Learning Programming Fundamental"/>
    <node LINK="http://zotero.org/groups/2366342/items/4JKM5VGU/file?page=1" TEXT="Key: QS7KQ5N5 &lt;br/&gt;&lt;br/&gt;Context: digital game‑based technology on English language learning (by the authors); &lt;br/&gt;&lt;br/&gt;Title: A scoping review of digital game-based technology on English language learning"/>
    <node LINK="http://zotero.org/groups/2366342/items/SYLN3YZV/file?page=2" TEXT="Key: AP894C4A &lt;br/&gt;&lt;br/&gt;Context: adaptive e-learning (by the authors); &lt;br/&gt;&lt;br/&gt;Title: A systematic literature review on adaptive gamification: Components, methods, and frameworks"/>
    <node LINK="http://zotero.org/groups/2366342/items/CFNJMTG7/file?page=1" TEXT="Key: R32D2JYR &lt;br/&gt;&lt;br/&gt;Context: e-marketing (by the authors); &lt;br/&gt;&lt;br/&gt;Title: A systematic mapping study on gamification applied to e-marketing"/>
    <node LINK="http://zotero.org/groups/2366342/items/TSBLY85U/file?page=1" TEXT="Key: YRSQ3TXK &lt;br/&gt;&lt;br/&gt;Context: adaptive gamication in education (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Adaptive Gamification in Education: A Literature Review of Current Trends and Developments"/>
    <node LINK="http://zotero.org/groups/2366342/items/TMSX55QH/file?page=2" TEXT="Key: 2TQEGCTQ &lt;br/&gt;&lt;br/&gt;Context: sustainability learning through serious games classified as motivational games (eco feedback games, gamification), and educational games (construction and management simulation, interactive fiction games, role-playing games, playful activities, procedural rhetoric games) (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Approaching Sustainability Learning Via Digital Serious Games"/>
    <node LINK="http://zotero.org/groups/2366342/items/BLJXTZCY/file?page=1" TEXT="Key: DP9LC2N7 &lt;br/&gt;&lt;br/&gt;Context: interventions for Autism Spectrum Disorder (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Designing Gamified Interventions for Autism Spectrum Disorder: A Systematic Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/FXL69DGN/file?page=1" TEXT="Key: 6INXC8HH &lt;br/&gt;&lt;br/&gt;Context: Massive Open Online Courses (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Engaging MOOC through gamification: Systematic mapping review"/>
    <node LINK="http://zotero.org/groups/2366342/items/ADG26DDQ/file?page=1" TEXT="Key: EKUQ6GZ6 &lt;br/&gt;&lt;br/&gt;Context: enterprise gamification (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Enterprise gamification systems and employment legislation: a systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/PHKXE7KX/file?page=2" TEXT="Key: RL9YEDGQ &lt;br/&gt;&lt;br/&gt;Context: educational context and gamification applied to engineering (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification as a strategy to improve students’ motivation and engagement in educational environments at engineering courses: bibliographic"/>
    <node LINK="http://zotero.org/groups/2366342/items/AX46XTC8/file?page=1" TEXT="Key: Y2I3R58N &lt;br/&gt;&lt;br/&gt;Context: different contexts (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification Framework: The Contribution of User Centered Design, Social Media Applications, Gaming and Psychology Concepts and Frameworks"/>
    <node LINK="http://zotero.org/groups/2366342/items/UDM6MNDX/file?page=1" TEXT="Key: D2DXYT2K &lt;br/&gt;&lt;br/&gt;Context: mental health and well-being (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification in apps and technologies for improving mental health and well-being: Systematic review"/>
    <node LINK="http://zotero.org/groups/2366342/items/24JK4VEG/file?page=1" TEXT="Key: MPMB45G9 &lt;br/&gt;&lt;br/&gt;Context: Cardio Pulmonary Resuscitation (CPR) or Basic Life Support (BLS) training (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification in CPR - A Review of Game Dynamics and Mechanics"/>
    <node LINK="http://zotero.org/groups/2366342/items/H5KSNXDS/file?page=1" TEXT="Key: SRBEUBEH &lt;br/&gt;&lt;br/&gt;Context: IoT (crowdsourcing-sensing, education, energy consumption, health care, industry, safe driving, smart building, sustainability) (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification in IoT application: A systematic mapping study"/>
    <node LINK="http://zotero.org/groups/2366342/items/U78FKG67/file?page=1" TEXT="Key: SQDTS6KC &lt;br/&gt;&lt;br/&gt;Context: teaching of management and education (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification in management education - A literature mapping"/>
    <node LINK="http://zotero.org/groups/2366342/items/SSENW62L/file?page=1" TEXT="Key: J4BHC26J &lt;br/&gt;&lt;br/&gt;Context: management (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Gamification in Management: analysis and research directions"/>
    <node LINK="http://zotero.org/groups/2366342/items/ERBZ46ZZ/file?page=NA" TEXT="Key: H696TSSJ &lt;br/&gt;&lt;br/&gt;Context: gamification concepts (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Main gamification concepts: A systematic mapping study"/>
    <node LINK="http://zotero.org/groups/2366342/items/ZHZEUC5A/file?page=1" TEXT="Key: GV7WT7H5 &lt;br/&gt;&lt;br/&gt;Context: tourism (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Review of benefit using gamification element for countryside tourism"/>
    <node LINK="http://zotero.org/groups/2366342/items/2IH7Y8RH/file?page=1" TEXT="Key: PA9ZB2CW &lt;br/&gt;&lt;br/&gt;Context: serious games, gamified application and educational software (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Serious game, gamified applications, educational software: A comparative study"/>
    <node LINK="http://zotero.org/groups/2366342/items/4TDM3GFC/file?page=1" TEXT="Key: XZR3LKIN &lt;br/&gt;&lt;br/&gt;Context: Corporate Training (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Serious Games and Gamification in the Corporate Training Environment: a Literature Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/KBI5Y6SI/file?page=" TEXT="Key: HTG2D2EL &lt;br/&gt;&lt;br/&gt;Context:  (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Serious gaming as a means of facilitating truly smart cities: a narrative review"/>
    <node LINK="http://zotero.org/groups/2366342/items/CYHRUKLX/file?page=1" TEXT="Key: 7GZALWCA &lt;br/&gt;&lt;br/&gt;Context: Online Learning Environments (by the authors); &lt;br/&gt;&lt;br/&gt;Title: The effects of gamification in online learning environments: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/QGNF2RLP/file?page=1" TEXT="Key: Z25JLEAQ &lt;br/&gt;&lt;br/&gt;Context: students ' academic achievement (by the authors); &lt;br/&gt;&lt;br/&gt;Title: The effects of gamification on students’ academic achievement: a meta-analysis study"/>
    <node LINK="http://zotero.org/groups/2366342/items/RY2DM4V4/file?page=1" TEXT="Key: 8NTDBRIF &lt;br/&gt;&lt;br/&gt;Context: Enterprise systems (by the authors); &lt;br/&gt;&lt;br/&gt;Title: The Hero's Journey to Innovation: Gamification in Enterprise Systems"/>
    <node LINK="http://zotero.org/groups/2366342/items/22XCUTKU/file?page=3" TEXT="Key: 9BNF29KS &lt;br/&gt;&lt;br/&gt;Context: students' learning in a university context (by the authors); &lt;br/&gt;&lt;br/&gt;Title: The Role of Gamification Techniques in Promoting Student Learning: A Review and Synthesis"/>
    <node LINK="http://zotero.org/groups/2366342/items/IHLIL5I5/file?page=1" TEXT="Key: 8L29NV9E &lt;br/&gt;&lt;br/&gt;Context: Learning English as a Second Language (by the authors); &lt;br/&gt;&lt;br/&gt;Title: Using gamification to support learning English as a second language: a systematic review"/>
  </node>
</map>
