<?xml version="1.0" encoding="UTF-8"?>
<map version="1.1.0">
  <node TEXT="Without classification">
    <node LINK="http://zotero.org/groups/2366342/items/89V5FFW7/file?page=2" TEXT="ID: 278d5b65bfaa576289fcb502d707fc69 &lt;br/&gt; RO(1): To shed some light on how these outcomes should be properly measured  &lt;br/&gt;&lt;br/&gt;Article Title: Using gamification in education: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/B5JPB9LV/file?page=1" TEXT="ID: b08daabb1c719bc0041ddd6ad110b8d5 &lt;br/&gt; RO(1): to inform survey researchers and practitioners of the current state of research on survey gamification and identifies potential areas for future research  &lt;br/&gt;&lt;br/&gt;Article Title: A Review of Issues in Gamified Surveys"/>
    <node LINK="http://zotero.org/groups/2366342/items/3PIVJ6GK/file?page=1" TEXT="ID: bdc814525da4e79a91ecc1954a4dc2f9 &lt;br/&gt; RO(1): to characterize the state of the art of this field identifying gaps and opportunities for further research  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in software engineering - A systematic mapping"/>
    <node LINK="http://zotero.org/groups/2366342/items/9QP9FGVV/file?page=1" TEXT="ID: bad859797134a28310f2923d261590f8 &lt;br/&gt; RO(1): Looking for models with motivational characteristics in an attempt to characterize the state of the art of this field, identifying gaps and tendencies for further research  &lt;br/&gt;&lt;br/&gt;Article Title: A systematic mapping study of gamification models oriented to motivational characteristics"/>
    <node LINK="http://zotero.org/groups/2366342/items/ZFNMEM6V/file?page=2" TEXT="ID: 73a49861451248a82ec840729c41c4c0 &lt;br/&gt; RO(1.4): Determine whether effects of the gamification feature on adherence varies across subgroup populations  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification and Adherence to Web-Based Mental Health Interventions: A Systematic Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/W68NI75Q/file?page=1" TEXT="ID: d4e78719a192a59397f366f75dd80f03 &lt;br/&gt; RO(2): to find gaps in literature that help developing future research directions  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification and learning performance: A systematic review of the literature"/>
    <node LINK="http://zotero.org/groups/2366342/items/ZFNMEM6V/file?page=2" TEXT="ID: d453fe6ad1eb6cef822c82af9307727d &lt;br/&gt; RO(1.3): Report current rates of adherence  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification and Adherence to Web-Based Mental Health Interventions: A Systematic Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/5DKWAQSJ/file?page=1" TEXT="ID: 0bca096b303365f7cfe25f0ecdc58774 &lt;br/&gt; RO(2): To identifying gaps and opportunities for further research  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in requirements engineering: A systematic review"/>
    <node LINK="http://zotero.org/groups/2366342/items/W4UVTB7N/file?page=2" TEXT="ID: 98ba270d64bd63e7b73f65784bcce800 &lt;br/&gt; RO(1.4): to present opportunities for future research  &lt;br/&gt;&lt;br/&gt;Article Title: Systematic review of gamification research in is education: A multi-method approach"/>
    <node LINK="http://zotero.org/groups/2366342/items/DJLTYYUF/file?page=2" TEXT="ID: 2c86400d278f7800b2fbece41ee6848f &lt;br/&gt; RO(1): infer what kinds of gamification efforts are effective in different kinds of crowdsourcing approaches  &lt;br/&gt;&lt;br/&gt;Article Title: Gamified crowdsourcing: Conceptualization, literature review, and future agenda"/>
    <node LINK="http://zotero.org/groups/2366342/items/ALSIWPM6/file?page=1" TEXT="ID: 4d1487b4a571b94ff4a759f733fca787 &lt;br/&gt; RO(1): to understand the overall effectiveness of a gamified approach for cognitive bias modiffication  &lt;br/&gt;&lt;br/&gt;Article Title: Gamified Cognitive Bias Modification Interventions for Psychiatric Disorders: Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/EQY43MLP/file?page=1" TEXT="ID: c5b753e15f98afce4e3ef897ced71e39 &lt;br/&gt; RO(1): to characterize how gamification has been explored to support software testing  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in software testing: A characterization study"/>
    <node LINK="http://zotero.org/groups/2366342/items/5DKWAQSJ/file?page=1" TEXT="ID: fd08078c6a70c62da275f72ba4a39751 &lt;br/&gt; RO(1): To characterize the state of the art of gamification in RE  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in requirements engineering: A systematic review"/>
    <node LINK="http://zotero.org/groups/2366342/items/R76JUB22/file?page=1" TEXT="ID: 4321c6323c3956c867aeeb172bc5bdd7 &lt;br/&gt; RO(1): to analyzes the state of the literature and explores the fit of gamification to learning in the engineering context  &lt;br/&gt;&lt;br/&gt;Article Title: Systematic literature review: An exploration of gamification in the context of engineering education"/>
    <node LINK="http://zotero.org/groups/2366342/items/3F4TY7AA/file?page=1" TEXT="ID: a8d14c72da26907c556bd10733890a7f &lt;br/&gt; RO(2): to define future gamification in the context of software project management  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification for improving software project management processes: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/3F4TY7AA/file?page=1" TEXT="ID: 791e2ca4202b5eb7c3a66a0fd24d6302 &lt;br/&gt; RO(1): to understand the current state of gamification as a strategy for improving processes associated with software project management  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification for improving software project management processes: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/ZDP4KPH8/file?page=2" TEXT="ID: eed425da99899cefb464646740c9678f &lt;br/&gt; RO(1): to understand the status quo and provide suggestions for future research concerning to gamification of production and logistics operations in organizational contexts  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification of production and logistics operations: Status quo and future directions"/>
    <node LINK="http://zotero.org/groups/2366342/items/YA6SB28S/file?page=1" TEXT="ID: 59af9b79409eda8172204d15504780fe &lt;br/&gt; RO(1): to compare and contrast gamification to similar concepts such as hedonic, persuasive and intrinsically motivating information systems  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification-A novel phenomenon or a new wrapping for existing concepts?"/>
    <node LINK="http://zotero.org/groups/2366342/items/UURKLF8G/file?page=1" TEXT="ID: 194474f8cabf00e73eb162080cdc6012 &lt;br/&gt; RO(1): to investigate how the literature evaluates gamification and compares its usage in educational environments through a systematic mapping  &lt;br/&gt;&lt;br/&gt;Article Title: Does gamification matter?: A systematic mapping about the evaluation of gamification in educational environments"/>
    <node LINK="http://zotero.org/groups/2366342/items/CCB3FSL7/file?page=1" TEXT="ID: a732279e9b0744e67301c66dc3fd259b &lt;br/&gt; RO(2): to identify gaps of current solutions that should be addressed by future work in the field of gamification analytics  &lt;br/&gt;&lt;br/&gt;Article Title: Tools for gamification analytics: A survey"/>
    <node LINK="http://zotero.org/groups/2366342/items/H4T9NS5C/file?page=2" TEXT="ID: 2c29f395814b45862ac513e7edad0225 &lt;br/&gt; RO(1): Analyse distribution patterns of the articles (both on a year and a journal basis)  &lt;br/&gt;&lt;br/&gt;Article Title: The use of gamification in education: a bibliometric and text mining analysis"/>
    <node LINK="http://zotero.org/groups/2366342/items/NEL8VNPT/file?page=1" TEXT="ID: 898a25a10a09627ffd0258f7acb393b5 &lt;br/&gt; RO(1): to discover the current state of the research on gamified software quality  &lt;br/&gt;&lt;br/&gt;Article Title: A Systematic Mapping Study on Gamified Software Quality"/>
    <node LINK="http://zotero.org/groups/2366342/items/EGSYEKAE/file?page=1" TEXT="ID: e175529814a976ba3f0e5e1473f8f34f &lt;br/&gt; RO(1): to synthesise earlier gamification findings, identifying the most utilised factors mentioned in the literature and their significance, providing a balanced theoretical supporting model for future gamification studies  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification and serious games: A literature meta-analysis and integrative model"/>
    <node LINK="http://zotero.org/groups/2366342/items/KPSZJH37/file?page=3" TEXT="ID: 8ff8327dd4253113bb73183f40a7bbce &lt;br/&gt; RO(1): synthesize the available literature on how the application of gamification to work is theoretically justified and can be guided  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in the workplace: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/W4UVTB7N/file?page=2" TEXT="ID: 65538f19d039aaab72fafc87db906073 &lt;br/&gt; RO(1.3): to highlight understudied areas  &lt;br/&gt;&lt;br/&gt;Article Title: Systematic review of gamification research in is education: A multi-method approach"/>
    <node LINK="http://zotero.org/groups/2366342/items/NEL8VNPT/file?page=1" TEXT="ID: 262500a2e19289077faddb996ea79b54 &lt;br/&gt; RO(2): to identify gaps that merit rigorous future investigation  &lt;br/&gt;&lt;br/&gt;Article Title: A Systematic Mapping Study on Gamified Software Quality"/>
    <node LINK="http://zotero.org/groups/2366342/items/ZFNMEM6V/file?page=2" TEXT="ID: c0e8d50e844f7578faebd51251c52bc4 &lt;br/&gt; RO(1.2): Identify gamification features that influence adherence  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification and Adherence to Web-Based Mental Health Interventions: A Systematic Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/7P67KPYE/file?page=3" TEXT="ID: 3839f3d13751f988efc0a4821b129e29 &lt;br/&gt; RO(1): to identify if gamification strategies are effective in increasing engagement in online programs  &lt;br/&gt;&lt;br/&gt;Article Title: Does gamification increase engagement with online programs? A systematic review"/>
    <node LINK="http://zotero.org/groups/2366342/items/PTATWLKY/file?page=1" TEXT="ID: 139107055bac5cb30f7dbdd307b416a0 &lt;br/&gt; RO(1): to investigate the personalized gamified learning studies  &lt;br/&gt;&lt;br/&gt;Article Title: A Review on Adopting Personalized Gamified Experience in the Learning Context"/>
    <node LINK="http://zotero.org/groups/2366342/items/AQG63SCH/file?page=1" TEXT="ID: cdbf5a55e2c63e864f9ce5ccaeb12c73 &lt;br/&gt; RO(1): to identify how gamified learning systems can be used and categorize its usefulness in higher education  &lt;br/&gt;&lt;br/&gt;Article Title: Gamified learning in higher education: A systematic review of the literature"/>
    <node LINK="http://zotero.org/groups/2366342/items/SY5JIJRU/file?page=1" TEXT="ID: 1d1e64a6f9befdfe023d4f95581d503c &lt;br/&gt; RO(1): to provide an overview of the research on gamification applied to education  &lt;br/&gt;&lt;br/&gt;Article Title: A systematic mapping on gamification applied to education"/>
    <node LINK="http://zotero.org/groups/2366342/items/2GCQL6NK/file?page=1" TEXT="ID: 765593c6f52154d4db96413395e29096 &lt;br/&gt; RO(1): to present an overview of gamification research  &lt;br/&gt;&lt;br/&gt;Article Title: A Wide View on Gamification"/>
    <node LINK="http://zotero.org/groups/2366342/items/BQ4NEBUZ/file?page=6" TEXT="ID: 2674cb4d7e372920e2f711ed33e0c752 &lt;br/&gt; RO(1): To provide an overview of the research on gamification in open and distance learning  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in Open and Distance Learning: A Systematic Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/W5EWFPQK/file?page=2" TEXT="ID: 92dd19866d68c0895d63f9a930f21836 &lt;br/&gt; RO(1): to shed light on the tendencies and emerging practices in the education area  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in education: A systematic mapping study"/>
    <node LINK="http://zotero.org/groups/2366342/items/PDB6L8NP/file?page=1" TEXT="ID: aae4c488058c70932ab6e8ad30a743df &lt;br/&gt; RO(2): to identify specific research needs, and suggest avenues for future research  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification - A new phenomenon in information systems research?"/>
    <node LINK="http://zotero.org/groups/2366342/items/RCP7K3FB/file?page=2" TEXT="ID: 0ca12c5781d56d59a63fe4e47e573a7f &lt;br/&gt; RO(1): to review current research and publications about gamification for education  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification for Education: Review of Current Publications"/>
    <node LINK="http://zotero.org/groups/2366342/items/DJLTYYUF/file?page=2" TEXT="ID: e7bd9b6b4281a9a43c09679b0dc6f0a5 &lt;br/&gt; RO(3): to outline a research agenda for future research  &lt;br/&gt;&lt;br/&gt;Article Title: Gamified crowdsourcing: Conceptualization, literature review, and future agenda"/>
    <node LINK="http://zotero.org/groups/2366342/items/5FHYJFR3/file?page=3" TEXT="ID: 8b85eefb1e46fb001eadc081332f0fdf &lt;br/&gt; RO(1): to show what current IS research in high ranked outlets discusses regarding Gamification as a basis for future research activities and as a knowledgebase  &lt;br/&gt;&lt;br/&gt;Article Title: A descriptive literature review and classification framework for Gamification in information systems"/>
    <node LINK="http://zotero.org/groups/2366342/items/F7TWMF26/file?page=2" TEXT="ID: 9d566303ce1fe2ba24d9f7875eaf28eb &lt;br/&gt; RO(1): to investigate the use of differing gamification implementations across different types of crowdsourcing initiatives  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in crowdsourcing: A review"/>
    <node LINK="http://zotero.org/groups/2366342/items/DJLTYYUF/file?page=2" TEXT="ID: d98155fe30d16c32ddf5960b4ea720d3 &lt;br/&gt; RO(2): derive recommendations for designers of gamified crowdsourcing systems  &lt;br/&gt;&lt;br/&gt;Article Title: Gamified crowdsourcing: Conceptualization, literature review, and future agenda"/>
    <node LINK="http://zotero.org/groups/2366342/items/5QCMGSKD/file?page=2" TEXT="ID: 20b25b253be9f2eb3d738a341bdfed85 &lt;br/&gt; RO(1): to show the usage of gamification and serious games on depression treatment  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification and serious games in depression care: A systematic mapping study"/>
    <node LINK="http://zotero.org/groups/2366342/items/6QGS7ZD7/file?page=2" TEXT="ID: c03736938d6c54dbe5d95ae00dbf3b59 &lt;br/&gt; RO(1): to systematically explore the theoretical and conceptual aspects of gamification in order to assess whether there is consensus on gamification as a distinct term and concept  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in theory and action: A survey"/>
    <node LINK="http://zotero.org/groups/2366342/items/5YLXK7VY/file?page=1" TEXT="ID: 28f4e85fc4d190f5a545605b7d19e639 &lt;br/&gt; RO(1): to completing a state of the art on the gamification design process  &lt;br/&gt;&lt;br/&gt;Article Title: A Literature Review of Gamification Design Frameworks"/>
    <node LINK="http://zotero.org/groups/2366342/items/KPSZJH37/file?page=3" TEXT="ID: 0381ccba76209632534011b623a35727 &lt;br/&gt; RO(2): providing evidence to clarify its benefits for human resources management  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in the workplace: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/5YLXK7VY/file?page=2" TEXT="ID: d1d48e132b2f3b11bacfd101e718ba5a &lt;br/&gt; RO(3): to identifying the existing gamification design frameworks and classifying them by their main features  &lt;br/&gt;&lt;br/&gt;Article Title: A Literature Review of Gamification Design Frameworks"/>
    <node LINK="http://zotero.org/groups/2366342/items/8MGXGRGM/file?page=2" TEXT="ID: 353e03cb36e0d1cebbcf4b296c9e9552 &lt;br/&gt; RO(2): to analyze existing gamification design frameworks in order to classify them and evaluate their suitability for higher-education environments  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification: a systematic review of design frameworks"/>
    <node LINK="http://zotero.org/groups/2366342/items/7HNL8CRV/file?page=1" TEXT="ID: aa155c095edd8a8c51db3ec6f47c39f5 &lt;br/&gt; RO(1): to identify problems and needs, focusing on the monitoring process of gamification strategies  &lt;br/&gt;&lt;br/&gt;Article Title: A systematic literature review on the gamification monitoring phase: How SPI standards can contribute to gamification maturity"/>
    <node LINK="http://zotero.org/groups/2366342/items/AK78SR4D/file?page=2" TEXT="ID: aa40b49a2b4cfe40e88d20964c167547 &lt;br/&gt; RO(1): discover gamification solutions to solve user engagement problems in different kinds of applications and websites, identify existing gaps, and suggest further studies  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification Solutions to Enhance Software User Engagement—A Systematic Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/89V5FFW7/file?page=2" TEXT="ID: 3818b70ad14d731697ba97440c885cd2 &lt;br/&gt; RO(2): To provide a map of current gamified systems outcomes, especially to classify them into the experiential-instrumental typology  &lt;br/&gt;&lt;br/&gt;Article Title: Using gamification in education: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/W4UVTB7N/file?page=2" TEXT="ID: 023d1c1f02705ced504ab8ac872187fb &lt;br/&gt; RO(1): systematically review existing research on gamification in IS education to identify common terminologies, identify trends in topics studied, highlight understudied areas, and, thus, present opportunities for future research  &lt;br/&gt;&lt;br/&gt;Article Title: Systematic review of gamification research in is education: A multi-method approach"/>
    <node LINK="http://zotero.org/groups/2366342/items/68Z32TLH/file?page=1" TEXT="ID: 75ccb01bcaee3944653d614429ca5cf7 &lt;br/&gt; RO(1): To shed further light on gamified learning experiences  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification and education: A literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/XXUDEFYP/file?page=23" TEXT="ID: 251378256e85917d1de3b0755d4b5e56 &lt;br/&gt; RO(2): outline the theoretical works underpinning the use of gamification in education, published within the review period   &lt;br/&gt;&lt;br/&gt;Article Title: Gamifying education: what is known, what is believed and what remains uncertain: a critical review"/>
    <node LINK="http://zotero.org/groups/2366342/items/ZEUQGR9V/file?page=1" TEXT="ID: 0bbda360afe672e39b2ea50007e1c46a &lt;br/&gt; RO(1): to identify themes emerging primarily from previous works, which focus on the different design elements in a digital badge system, dependencies between badges and how they are used across the curriculum  &lt;br/&gt;&lt;br/&gt;Article Title: Educational functions and design of badge systems: A conceptual literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/AAP5YV7B/file?page=3" TEXT="ID: d79dfed7081586d02fa15bc10b4a808f &lt;br/&gt; RO(2): to enrich the body of knowledge in the field of gamification by presenting a taxonomy that supports practitioners and researchers to decide which game design elements to use and to combine  &lt;br/&gt;&lt;br/&gt;Article Title: Is it all about having fun? - Developing a taxonomy to gamify information systems"/>
    <node LINK="http://zotero.org/groups/2366342/items/F2EDJU4Y/file?page=1" TEXT="ID: a191d837ad3d652261a03cd3c834e8e9 &lt;br/&gt; RO(1): reviewed health apps containing gaming elements analysing their embedded behaviour change techniques  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification for health promotion: systematic review of behaviour change techniques in smartphone apps"/>
    <node LINK="http://zotero.org/groups/2366342/items/RQLWQJVM/file?page=3" TEXT="ID: 879b416e0b6bff749339fe5952c76122 &lt;br/&gt; RO(1): to review and analyze the existing research contributions that explicitly identify the game elements employed in eHealth  &lt;br/&gt;&lt;br/&gt;Article Title: A systematic review of gamification in e-Health"/>
    <node LINK="http://zotero.org/groups/2366342/items/5VCZGAB4/file?page=2" TEXT="ID: 11032f23fd923f4540d0023bb211ee89 &lt;br/&gt; RO(1): to present a gamification requirements catalog for ES, including the personality types of students  &lt;br/&gt;&lt;br/&gt;Article Title: A gamification requirements catalog for educational software: Results from a systematic literature review and a survey with experts"/>
    <node LINK="http://zotero.org/groups/2366342/items/ZFNMEM6V/file?page=1" TEXT="ID: 64985264e31ca3acf3f3032d9b82b567 &lt;br/&gt; RO(1): to examine whether gaming features predict or influence reported rates of program adherence in Web-based interventions designed to manage CMDs and well-being  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification and Adherence to Web-Based Mental Health Interventions: A Systematic Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/AY39YFUS/file?page=1" TEXT="ID: 17e1461864751fab25bcbc86f07fa777 &lt;br/&gt; RO(1): to identify good practices that can be used to design meaningful learning experiences and to inform future research related to game - based learning  &lt;br/&gt;&lt;br/&gt;Article Title: A review of research questions, theories and methodologies for game- based learning"/>
    <node LINK="http://zotero.org/groups/2366342/items/TGV6N9SZ/file?page=3" TEXT="ID: c00d57a41746be766891b0acd52e7b49 &lt;br/&gt; RO(1): to identify and analyze game related approaches from the purpose of mapping their learning objectives to software engineering knowledge areas from the perspective of researchers, educators, and learners in the context of software engineering education  &lt;br/&gt;&lt;br/&gt;Article Title: Games for learning: Bridging game-related education methods to software engineering knowledge areas"/>
    <node LINK="http://zotero.org/groups/2366342/items/MEE3FCH3/file?page=2" TEXT="ID: 42ba2e1cfb4e7e97776ac47cb761f350 &lt;br/&gt; RO(1): to comprehensively review and synthesize the extant literature on the concept of gamification  &lt;br/&gt;&lt;br/&gt;Article Title: The rise of motivational information systems: A review of gamification research"/>
    <node LINK="http://zotero.org/groups/2366342/items/BEGGW57J/file?page=2" TEXT="ID: 2969705c4bc8082303ba83c8bd9cad02 &lt;br/&gt; RO(1): to identify the most popular elements of gamification that are being used in healthcare contexts  &lt;br/&gt;&lt;br/&gt;Article Title: Health Care Gamification: A Study of Game Mechanics and Elements"/>
    <node LINK="http://zotero.org/groups/2366342/items/3VQR92B5/file?page=3" TEXT="ID: 26a358a7a9ca0d84adbca80b3f54cf8a &lt;br/&gt; RO(1): to synthesize outcomes of existing research on adaptive gamification in the body of gamification literature and develop main challenges  &lt;br/&gt;&lt;br/&gt;Article Title: Towards adaptive gamification: A synthesis of current developments"/>
    <node LINK="http://zotero.org/groups/2366342/items/BEGGW57J/file?page=3" TEXT="ID: c137ff27bd8d6f39a7f1ec8b2f693bcf &lt;br/&gt; RO(3): to provide a short list of popular gamification elements to help reach a consensus on defining gamification in health research  &lt;br/&gt;&lt;br/&gt;Article Title: Health Care Gamification: A Study of Game Mechanics and Elements"/>
    <node LINK="http://zotero.org/groups/2366342/items/H4T9NS5C/file?page=2" TEXT="ID: be770842aefe1c352c94a37831b4b60a &lt;br/&gt; RO(3): Identify the most relevant researchers and institutions involved in this research area  &lt;br/&gt;&lt;br/&gt;Article Title: The use of gamification in education: a bibliometric and text mining analysis"/>
    <node LINK="http://zotero.org/groups/2366342/items/ZFNMEM6V/file?page=2" TEXT="ID: 149a0cb96fa1e09d4032b3328fdf3b28 &lt;br/&gt; RO(1.1): Identify studies that have incorporated gaming features into the design of their intervention to improve outcomes for CMDs and well-being  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification and Adherence to Web-Based Mental Health Interventions: A Systematic Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/ALSIWPM6/file?page=1" TEXT="ID: 558ab6da4d2c5e4140ab70517b3dc739 &lt;br/&gt; RO(2): to inform future research that seeks to integrate gamification technologies into existing conventional bias modification interventions  &lt;br/&gt;&lt;br/&gt;Article Title: Gamified Cognitive Bias Modification Interventions for Psychiatric Disorders: Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/PDB6L8NP/file?page=1" TEXT="ID: fb9487a6dd8f13b672d64223362af810 &lt;br/&gt; RO(1): to identify the overlap between IS and gamification research  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification - A new phenomenon in information systems research?"/>
    <node LINK="http://zotero.org/groups/2366342/items/FJ7VYX6E/file?page=1" TEXT="ID: badc8b610eb2323ed3c79ade861492de &lt;br/&gt; RO(1): to determine the prevalence of different reward types, specifically point systems, within gamified interventions  &lt;br/&gt;&lt;br/&gt;Article Title: What's the Point?: A Review of Reward Systems Implemented in Gamification Interventions"/>
    <node LINK="http://zotero.org/groups/2366342/items/NKEUQSFJ/file?page=2" TEXT="ID: 69521a8ef3117cca80056dcf48711d2c &lt;br/&gt; RO(3): to provide a simple way to classify the features, in order to identify the relationships between them and the gaps of their implementations  &lt;br/&gt;&lt;br/&gt;Article Title: Gamified In-Home Rehabilitation for Stroke Survivors: Analytical Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/8MGXGRGM/file?page=2" TEXT="ID: 060fb5c4ab44f19969110ebad9029d72 &lt;br/&gt; RO(1): to identify the relevant state-of-the art literature on the gamification design process  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification: a systematic review of design frameworks"/>
    <node LINK="http://zotero.org/groups/2366342/items/NKEUQSFJ/file?page=2" TEXT="ID: 6f27e98a415c008e50db2d5c4c3b0d23 &lt;br/&gt; RO(1): to provide a literature review of the developed and tested gamified systems for in-home stroke rehabilitation  &lt;br/&gt;&lt;br/&gt;Article Title: Gamified In-Home Rehabilitation for Stroke Survivors: Analytical Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/CCB3FSL7/file?page=1" TEXT="ID: 1a9a8fcde27cddf0a57c7865fad89396 &lt;br/&gt; RO(1): to identify relevant software solutions and assesses them with regards to their fulfillment of user requirements in the gamification analytics domain  &lt;br/&gt;&lt;br/&gt;Article Title: Tools for gamification analytics: A survey"/>
    <node LINK="http://zotero.org/groups/2366342/items/XXUDEFYP/file?page=1" TEXT="ID: 8e19b53abd9a8454987c3b9e838927a4 &lt;br/&gt; RO(1): to shed a more realistic light on the research in this field by focusing on empirical evidence rather than on potentialities, beliefs or preferences  &lt;br/&gt;&lt;br/&gt;Article Title: Gamifying education: what is known, what is believed and what remains uncertain: a critical review"/>
    <node LINK="http://zotero.org/groups/2366342/items/MEE3FCH3/file?page=2" TEXT="ID: 1950ced78c6ec858ebae8bc48fa8db31 &lt;br/&gt; RO(2): to theorize and delineate a further research agenda for the research of gamification and motivational information systems within the information systems research field  &lt;br/&gt;&lt;br/&gt;Article Title: The rise of motivational information systems: A review of gamification research"/>
    <node LINK="http://zotero.org/groups/2366342/items/YU3A4YPR/file?page=2" TEXT="ID: be3a87a76038ee3114e21be61745f721 &lt;br/&gt; RO(2): to collect all selected game design elements and to identify new game design elements that might be proposed by previous researchers  &lt;br/&gt;&lt;br/&gt;Article Title: A review of intrinsic motivation elements in gamified online learning"/>
    <node LINK="http://zotero.org/groups/2366342/items/5YLXK7VY/file?page=1" TEXT="ID: 80cabfe4f203986e7503ced40292b2d3 &lt;br/&gt; RO(2): to analyse the relationship between the gamification and game design processes  &lt;br/&gt;&lt;br/&gt;Article Title: A Literature Review of Gamification Design Frameworks"/>
    <node LINK="http://zotero.org/groups/2366342/items/YU3A4YPR/file?page=2" TEXT="ID: 82e2f350a844ce72e7bae3c73b147dbd &lt;br/&gt; RO(3): to analyze the existence of intrinsic motivational elements in online learning based on game design elements and methods used by researchers  &lt;br/&gt;&lt;br/&gt;Article Title: A review of intrinsic motivation elements in gamified online learning"/>
    <node LINK="http://zotero.org/groups/2366342/items/NKEUQSFJ/file?page=2" TEXT="ID: 2247cb62edb1d4cecd6d170e14657fe8 &lt;br/&gt; RO(2): to identify and explain the most used features of these systems  &lt;br/&gt;&lt;br/&gt;Article Title: Gamified In-Home Rehabilitation for Stroke Survivors: Analytical Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/6RBHK2DA/file?page=1" TEXT="ID: e136c67282b91ffbd3e992caa67324b8 &lt;br/&gt; RO(1): to discuss how game-related methods have been used in the context of software engineering education by means of a systematic mapping study  &lt;br/&gt;&lt;br/&gt;Article Title: A systematic mapping study on game-related methods for software engineering education"/>
    <node LINK="http://zotero.org/groups/2366342/items/NB66S9QS/file?page=2" TEXT="ID: 3328cc6652a39cca6df2e27a9ed7005b &lt;br/&gt; RO(1): to investigate the use of game elements in the context of software business landscapes &#10;&#10;   &lt;br/&gt;&lt;br/&gt;Article Title: A systematic investigation into the use of game elements in the context of software business landscapes: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/H4T9NS5C/file?page=2" TEXT="ID: 70d172bd30a7f11d76215ce0e91097b4 &lt;br/&gt; RO(2): Analyse the main keywords used by researchers  &lt;br/&gt;&lt;br/&gt;Article Title: The use of gamification in education: a bibliometric and text mining analysis"/>
    <node LINK="http://zotero.org/groups/2366342/items/PQ5QBBU6/file?page=1" TEXT="ID: eb29878206b4a8e517f9a4d126d77c7d &lt;br/&gt; RO(1): to examine published research on the use of videogames for diabetes management  &lt;br/&gt;&lt;br/&gt;Article Title: The Use of Videogames, Gamification, and Virtual Environments in the Self-Management of Diabetes: A Systematic Review of Evidence"/>
    <node LINK="http://zotero.org/groups/2366342/items/FSEVDEN3/file?page=2" TEXT="ID: 372a3dcff23a97adab7c9cfef410ad7b &lt;br/&gt; RO(1): to the understanding of gamification by reviewing the existing body of empirical research on the topic  &lt;br/&gt;&lt;br/&gt;Article Title: Does gamification work? - A literature review of empirical studies on gamification"/>
    <node LINK="http://zotero.org/groups/2366342/items/H4T9NS5C/file?page=2" TEXT="ID: aa4a9924b78d34eebb668db18aebf872 &lt;br/&gt; RO(4): Identify the main topics and themes used by researchers  &lt;br/&gt;&lt;br/&gt;Article Title: The use of gamification in education: a bibliometric and text mining analysis"/>
    <node LINK="http://zotero.org/groups/2366342/items/6QGS7ZD7/file?page=2" TEXT="ID: 3dd48277ba5e9d1068f7015d126605da &lt;br/&gt; RO(3): to establish what links, if any, there are between theoretical work and applied work on gamification  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in theory and action: A survey"/>
    <node LINK="http://zotero.org/groups/2366342/items/83UPKQA9/file?page=1" TEXT="ID: 5f4b6cfa3a70e28b86311d9d9b75bfe6 &lt;br/&gt; RO(1): to examine the impacts of game-based/gamified learning on dispositions, cognitive abilities and behaviors of learners aged 6 - 12, and to identify the factors that contributed to these impacts  &lt;br/&gt;&lt;br/&gt;Article Title: Game-play: Effects of online gamified and game-based learning on dispositions, abilities and behaviours of primary learners"/>
    <node LINK="http://zotero.org/groups/2366342/items/PF9N57QW/file?page=2" TEXT="ID: 73d209b0e10572860bf45435ab9f85f7 &lt;br/&gt; RO(1): to find the different approaches, models, methods, components, etc. that have an element of games, serious games, gami cation or simulation which are looking for resolving the two problems: high costs and motivation in organization training  &lt;br/&gt;&lt;br/&gt;Article Title: A systematic literature review on organizational training using game-based learning"/>
    <node LINK="http://zotero.org/groups/2366342/items/ZFNMEM6V/file?page=2" TEXT="ID: fd8345a6c2492e813f546d193cb4aaf0 &lt;br/&gt; RO(1.5): Identify all terms commonly used to report adherence and maintenance with Web-based CMD and well-being and report the extent to which these are commonly reported in studies  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification and Adherence to Web-Based Mental Health Interventions: A Systematic Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/2929SPWN/file?page=2" TEXT="ID: c4cda40aa06991d996044b6718e80a69 &lt;br/&gt; RO(1): to explore which is the current state of the implementation of gamification in MOOCs  &lt;br/&gt;&lt;br/&gt;Article Title: How gamification is being implemented in MOOCs? A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/UK48D9L7/file?page=3" TEXT="ID: 9efe71ac8c5f260f59947aa94c986b8e &lt;br/&gt; RO(1): to conduct a systematic literature review of research studies on gamebased learning and gamification conducted in Asian K-12 school  &lt;br/&gt;&lt;br/&gt;Article Title: A systematic literature review of game-based learning and gamification research in Asia"/>
    <node LINK="http://zotero.org/groups/2366342/items/S69ERHTA/file?page=1" TEXT="ID: 1f4b3e1db2d2ea9c5dc9e7ea59a4788b &lt;br/&gt; RO(1): to assess the findings of the quality literatures, such that the predecessors’ contributions of applying gamification to healthcare system  &lt;br/&gt;&lt;br/&gt;Article Title: A survey of gamification for healthcare system"/>
    <node LINK="http://zotero.org/groups/2366342/items/UK48D9L7/file?page=3" TEXT="ID: 7ba15970070144e695ef6aed2663a457 &lt;br/&gt; RO(1): to present a comprehensive analysis of what the body of accumulated research informs us of the impact of games in Asian educational settings and to draw implications for future research directions  &lt;br/&gt;&lt;br/&gt;Article Title: A systematic literature review of game-based learning and gamification research in Asia"/>
    <node LINK="http://zotero.org/groups/2366342/items/5F36YA7T/file?page=2" TEXT="ID: 398843d2b9c542588cd74da6ff649e38 &lt;br/&gt; RO(1): the purpose of this review is to develop a conceptual model unifying gamification literature across different domains to guide further research in understanding the process of mechanics, psychological mediators and contextual outcomes  &lt;br/&gt;&lt;br/&gt;Article Title: An interdisciplinary perspective on gamification: Mechanics, psychological mediators and outcomes"/>
    <node LINK="http://zotero.org/groups/2366342/items/KY3DI2Q4/file?page=1" TEXT="ID: 2d05d76927588009f7eeb7cf93c83642 &lt;br/&gt; RO(1):   to develop a conceptual model of applying games to management education through a systematic literature review, focusing on the most relevant literature on the application of gamification to educational contexts in order to grasp gamification's main themes and constructs.  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in a Management Education: Systematic Literature Review and a Proposal of a Conceptual Research Model"/>
    <node LINK="http://zotero.org/groups/2366342/items/H4T9NS5C/file?page=2" TEXT="ID: c1928709613fdb623d33b3e5e244291d &lt;br/&gt; RO(5): Identify the main methodological approach (quantitative, qualitative or mixed-methods research) and designs (i.e., true experiments) used by researchers  &lt;br/&gt;&lt;br/&gt;Article Title: The use of gamification in education: a bibliometric and text mining analysis"/>
    <node LINK="http://zotero.org/groups/2366342/items/YU3A4YPR/file?page=2" TEXT="ID: 50ca914714dc14f50c750c9cc53821a2 &lt;br/&gt; RO(1): to investigate the utilization of gamification in online learning, such as; research objectives, framework or models, other approaches that may be adopted or used, types of platforms and courses selected, testing methods, and research results achieved  &lt;br/&gt;&lt;br/&gt;Article Title: A review of intrinsic motivation elements in gamified online learning"/>
    <node LINK="http://zotero.org/groups/2366342/items/3VQR92B5/file?page=3" TEXT="ID: 845e5e1d49baedb5fb8119614f880e84 &lt;br/&gt; RO(2): to explore related research, which is contributing to adaptive gamification research  &lt;br/&gt;&lt;br/&gt;Article Title: Towards adaptive gamification: A synthesis of current developments"/>
    <node LINK="http://zotero.org/groups/2366342/items/D4F497R6/file?page=2" TEXT="ID: 69867e7538ebc59453047093b4d6f2eb &lt;br/&gt; RO(1): aim at answering the following research question :What are the negative eects that can occur in gamication when applied to educational contexts?  &lt;br/&gt;&lt;br/&gt;Article Title: The dark side of gamification: An overview of negative effects of gamification in education"/>
    <node LINK="http://zotero.org/groups/2366342/items/D4F497R6/file?page=2" TEXT="ID: c9c38d2337b09ba1a7b31298d14cc5fa &lt;br/&gt; RO(1): to answer the research question: What are the negative effects that can occur in gamication when applied to educational contexts?  &lt;br/&gt;&lt;br/&gt;Article Title: The dark side of gamification: An overview of negative effects of gamification in education"/>
    <node LINK="http://zotero.org/groups/2366342/items/3KK9S6TH/file?page=2" TEXT="ID: 72a49a9296a0174bcdc8108887b6bf78 &lt;br/&gt; RO(1): to identify and analyze game-related methods aiming to understand their application in the context of public health education, in particular, those designed to support awareness and behavior changes for dengue prevention  &lt;br/&gt;&lt;br/&gt;Article Title: A Systematic Mapping of Game-Based Methods to Tackle a Public Health Problem"/>
    <node LINK="http://zotero.org/groups/2366342/items/RV2UBJ99/file?page=3" TEXT="ID: a718d1cb063445b95a3a5051516b37f3 &lt;br/&gt; RO(1): to develop an exploratory study regarding the long-term engagement in digital health behaviour change interventions, and concentrate, as an initial approach, on systems designed for health promotion  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification applied for health promotion: Does it really foster long-term engagement? A scoping review"/>
    <node LINK="http://zotero.org/groups/2366342/items/6RBHK2DA/file?page=1" TEXT="ID: 3169672e9788221fcd42ed2bd5fbf875 &lt;br/&gt; RO(2): to investigate how these game-related methods support specific knowledge areas from software engineering  &lt;br/&gt;&lt;br/&gt;Article Title: A systematic mapping study on game-related methods for software engineering education"/>
    <node LINK="http://zotero.org/groups/2366342/items/2EF4HZHZ/file?page=1" TEXT="ID: ea0f1b248c525db0ad72bb319e8b640d &lt;br/&gt; RO(1): to model correlations documented in literature between RE tasks, stakeholder motivation and engagement, and gamification  &lt;br/&gt;&lt;br/&gt;Article Title: Leveraging motivational theories for designing gamification for RE"/>
    <node LINK="http://zotero.org/groups/2366342/items/RQLWQJVM/file?page=1" TEXT="ID: 5e247e84e68a941e45eabd5e5e5dd179 &lt;br/&gt; RO(1): to summarize the current knowledge regarding gamified e-Health applications  &lt;br/&gt;&lt;br/&gt;Article Title: A systematic review of gamification in e-Health"/>
    <node LINK="http://zotero.org/groups/2366342/items/DFEK6V3A/file?page=2" TEXT="ID: 0003be3665c5b93a0743425fae799131 &lt;br/&gt; RO(1): to provide helpful information about the state of practice of gamification in SE education, trends and challenges.  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in software engineering education: A systematic mapping"/>
    <node LINK="http://zotero.org/groups/2366342/items/YWZLLIUS/file?page=1" TEXT="ID: 1d417a3d08589137d0e15761b892b75b &lt;br/&gt; RO(1): to evaluate the effectiveness of serious gaming/gamification for health professions education compared with traditional learning, other types of digital education, or other serious gaming/gamification interventions in terms of patient outcomes, knowledge, skills, professional attitudes, and satisfaction (primary outcomes) as well as economic outcomes of education and adverse events (secondary outcomes)  &lt;br/&gt;&lt;br/&gt;Article Title: Serious gaming and gamification education in health professions: systematic review"/>
    <node LINK="http://zotero.org/groups/2366342/items/GUTAIAKH/file?page=2" TEXT="ID: 36326a54eb772fabd9c98108f6f07ad7 &lt;br/&gt; RO(1): to determine if means of gamification, which are used to support or to enable mobile application, could be an effective way to support therapy, diagnosis or prevention in healthcare  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification for mHealth - A review of playful mobile healthcare"/>
    <node LINK="http://zotero.org/groups/2366342/items/YABDS4GN/file?page=1" TEXT="ID: bc4ecee42e04241fbadd8378176043dc &lt;br/&gt; RO(1): to provide an overview of studies on gamification in MOOCs, types of research studies, theories applied, gamification elements implemented, methods of implementation, the overall impact of gamification in MOOCs, and the challenges faced by researchers and practitioners when implementing gamification in MOOCs  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in MOOCs: A review of the state of the art"/>
    <node LINK="http://zotero.org/groups/2366342/items/GZPP6FJE/file?page=1" TEXT="ID: a526827bdf892412d30b433065c3fb78 &lt;br/&gt; RO(1): to explore and evaluate the ways in which gamification has already been used for cognitive training and assessment purposes  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification of Cognitive Assessment and Cognitive Training: A Systematic Review of Applications and Efficacy"/>
    <node LINK="http://zotero.org/groups/2366342/items/NY3HCY5C/file?page=2" TEXT="ID: 6df6b9ac2f4010b8040e609584899fb2 &lt;br/&gt; RO(1): to propose and evaluates a comprehensive framework of engagement in gamified learning that covers all its aspects &#10;&#10;   &lt;br/&gt;&lt;br/&gt;Article Title: Developing a comprehensive Engagement framework of gamification for reflective learning"/>
    <node LINK="http://zotero.org/groups/2366342/items/8AI5LB5S/file?page=2" TEXT="ID: 1bee831ce45c2bb44148233c6a6d8371 &lt;br/&gt; RO(1): explores the possibility of using gamification as a tool in education to increase student engagement and motivation  &lt;br/&gt;&lt;br/&gt;Article Title: The role of gamification in education - a literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/G8TH79GQ/file?page=2" TEXT="ID: 1530a113320d8f0a225d9d4bb40d442f &lt;br/&gt; RO(1): to examine empirical evidence reported on the value of applied games within the domain of domestic energy consumption and conservation (both e ciency gains and actual reduction)  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification and serious games within the domain of domestic energy consumption: A systematic review"/>
    <node LINK="http://zotero.org/groups/2366342/items/MGZ6GW94/file?page=2" TEXT="ID: b663f664a887e65c2de7ae3eeb68e59a &lt;br/&gt; RO(1): to analyze experimental studies focused on the use of applied gaming to engage consumers in pro-environmental behaviors (PEBs) for energy efficiency, with the aim to provide crucial indications for future studies and interventions  &lt;br/&gt;&lt;br/&gt;Article Title: Gaming for Earth: Serious games and gamification to engage consumers in pro-environmental behaviours for energy efficiency"/>
    <node LINK="http://zotero.org/groups/2366342/items/BQ4NEBUZ/file?page=6" TEXT="ID: 5f68a4b516833360dae5765d9192eb2d &lt;br/&gt; RO(2): To provide practical information to integrate game elements to online programs successfully  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in Open and Distance Learning: A Systematic Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/GJLS77LT/file?page=1" TEXT="ID: 61363d1b3c6df2569489b521106c92c8 &lt;br/&gt; RO(1): an overview of how the embedding of gamification in OCL can enhance participation among novice programing students  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in online collaborative learning for programming courses: A literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/X53YHVAX/file?page=1" TEXT="ID: a72085b30e85155eabd59ebcec38ad13 &lt;br/&gt; RO(1): examines the potential of gamification to improve waste management practices among schoolchildren   &lt;br/&gt;&lt;br/&gt;Article Title: A review of the applicability of gamification and game-based learning to improve household-level waste management practices among schoolchildren"/>
    <node LINK="http://zotero.org/groups/2366342/items/PQ5QBBU6/file?page=1" TEXT="ID: 15fa136b16659ccc052d332a50cbac11 &lt;br/&gt; RO(2): to understand whether games, gamification, and virtual environments can be used for diabetes self-management  &lt;br/&gt;&lt;br/&gt;Article Title: The Use of Videogames, Gamification, and Virtual Environments in the Self-Management of Diabetes: A Systematic Review of Evidence"/>
    <node LINK="http://zotero.org/groups/2366342/items/SGTGM7SQ/file?page=1" TEXT="ID: d9f4d32692a4c3c7fa64ac4043d0bb89 &lt;br/&gt; RO(1): to present an analysis of the existing gamification elements applied in teaching and learning to enhance learning engagement  &lt;br/&gt;&lt;br/&gt;Article Title: An analysis of gamification elements in online learning to enhance learning engagement"/>
    <node LINK="http://zotero.org/groups/2366342/items/HU7QC9C3/file?page=2" TEXT="ID: 2d1280a3725349ff471004392f78354f &lt;br/&gt; RO(1): to identify and analyze gamification elements applied in virtual learning environments  &lt;br/&gt;&lt;br/&gt;Article Title: Elements of gamification in virtual learning environments: A systematic review"/>
    <node LINK="http://zotero.org/groups/2366342/items/W68NI75Q/file?page=1" TEXT="ID: 24597d3bfb11a672073cb12a0e457abf &lt;br/&gt; RO(1): to provide the current state-of-the-art on the topic  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification and learning performance: A systematic review of the literature"/>
    <node LINK="http://zotero.org/groups/2366342/items/8GV9EAM4/file?page=1" TEXT="ID: 6ea483e9c20d7a0e2597be46be600456 &lt;br/&gt; RO(1): to provide a current state-of-the-art of empirical work regarding gamification  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in higher education and STEM : a systematic review of literature"/>
    <node LINK="http://zotero.org/groups/2366342/items/EH6UY6U2/file?page=3" TEXT="ID: 7a52590e9174780bf20cde74cd7368a3 &lt;br/&gt; RO(1): to identify and map trends in gamification studies &#10;&#10; &#10;&#10; &#10;&#10;   &lt;br/&gt;&lt;br/&gt;Article Title: A systematic review of gamification research: In pursuit of homo ludens"/>
    <node LINK="http://zotero.org/groups/2366342/items/42Q3VTRN/file?page=2" TEXT="ID: fe782c05ad9d6950fb0c65cab5d297f4 &lt;br/&gt; RO(1): to make a state-of-the-art survey that could identify an accessible gamified application for cognitive memory training of elderly people  &lt;br/&gt;&lt;br/&gt;Article Title: Accessibility and Gamification Applied to Cognitive Training and Memory Improvement"/>
    <node LINK="http://zotero.org/groups/2366342/items/6QGS7ZD7/file?page=2" TEXT="ID: b307613190f62b55d325fb92451327b4 &lt;br/&gt; RO(2): to provide a multidisciplinary review on the state-of-the-art of applied gamification research  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in theory and action: A survey"/>
    <node LINK="http://zotero.org/groups/2366342/items/W4UVTB7N/file?page=2" TEXT="ID: b54a1f3c8e5bdd09bd4f39a8e7402b31 &lt;br/&gt; RO(1.1): to identify common terminologies  &lt;br/&gt;&lt;br/&gt;Article Title: Systematic review of gamification research in is education: A multi-method approach"/>
    <node LINK="http://zotero.org/groups/2366342/items/AAP5YV7B/file?page=2" TEXT="ID: e785f6c335d7f406231d13e6836c4ca0 &lt;br/&gt; RO(2): to consolidate the state of the art of gamification research and rigorously develop a gamification taxonomy  &lt;br/&gt;&lt;br/&gt;Article Title: Is it all about having fun? - Developing a taxonomy to gamify information systems"/>
    <node LINK="http://zotero.org/groups/2366342/items/4FDSTPP7/file?page=1" TEXT="ID: 45369fa14c1becaf111ca2a1e138a11e &lt;br/&gt; RO(1): to identify the most common gamification mechanics in the promotion of behavioral change  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification mechanics for behavioral change: A systematic review and proposed taxonomy"/>
    <node LINK="http://zotero.org/groups/2366342/items/4FDSTPP7/file?page=1" TEXT="ID: cb8893379ab30ed84470be18617f9236 &lt;br/&gt; RO(2): to propose a taxonomy of gamification mechanics that can be applied in health to promote behavioral changes  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification mechanics for behavioral change: A systematic review and proposed taxonomy"/>
    <node LINK="http://zotero.org/groups/2366342/items/8GV9EAM4/file?page=1" TEXT="ID: 78b6609386aecd06dd3238096aff9d95 &lt;br/&gt; RO(2): to find gaps in existing studies  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in higher education and STEM : a systematic review of literature"/>
    <node LINK="http://zotero.org/groups/2366342/items/W4UVTB7N/file?page=2" TEXT="ID: 1c3225c2daafc848cdaf96cb1e2a46d2 &lt;br/&gt; RO(1.2): to identify trends in topics studied  &lt;br/&gt;&lt;br/&gt;Article Title: Systematic review of gamification research in is education: A multi-method approach"/>
    <node LINK="http://zotero.org/groups/2366342/items/RYA447QD/file?page=1" TEXT="ID: 3a71b6fef3a2cb2dc45cf4158c76c49f &lt;br/&gt; RO(1): to discover the quality aspects to prioritize and highlight in the design of a Gamified solution  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification design frameworks: A systematic mapping study"/>
    <node LINK="http://zotero.org/groups/2366342/items/LYU6XR5U/file?page=1" TEXT="ID: 86f1ad0ac8013db2a669dff4b69e2cf8 &lt;br/&gt; RO(1): to identify gamification strategies that are employed in mobile applications  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification strategies for mobile device applications: A systematic review"/>
    <node LINK="http://zotero.org/groups/2366342/items/SY5JIJRU/file?page=1" TEXT="ID: 4c5af033a5c3676bac6eb7f70d668b5f &lt;br/&gt; RO(2): to identify the existence of initiatives that use gamification in CSCL environments  &lt;br/&gt;&lt;br/&gt;Article Title: A systematic mapping on gamification applied to education"/>
    <node LINK="http://zotero.org/groups/2366342/items/E8WSFLSN/file?page=2" TEXT="ID: 9e59320cd7058b9520a0bfae8dec7645 &lt;br/&gt; RO(1): To assess to what extent gamification is a monodisciplinary or multi-disciplinary research field  &lt;br/&gt;&lt;br/&gt;Article Title: How multidisciplinary is gamification research? Results from a scoping review"/>
    <node LINK="http://zotero.org/groups/2366342/items/WAV7W72K/file?page=2" TEXT="ID: 266631bab60a835347d9a658d5c1545a &lt;br/&gt; RO(1): to assess the entire domain of gamification and its applications  &lt;br/&gt;&lt;br/&gt;Article Title: Publication trends in gamification: A systematic mapping study"/>
    <node LINK="http://zotero.org/groups/2366342/items/LGIJHJ49/file?page=3" TEXT="ID: d90bea86f3f4d63f7f28b8b34eb00b50 &lt;br/&gt; RO(1): to review on the effectiveness and quality of health and well-being gamification applications   &lt;br/&gt;&lt;br/&gt;Article Title: Gamification for health and wellbeing: A systematic review of the literature"/>
    <node LINK="http://zotero.org/groups/2366342/items/8P9TYZAQ/file?page=3" TEXT="ID: c53fe7a88b43dd4affa804558b7ea0d5 &lt;br/&gt; RO(1): analyze how gamification has been implemented in the studies in the education domain   &lt;br/&gt;&lt;br/&gt;Article Title: Gamification of education and learning: A review of empirical literature"/>
    <node LINK="http://zotero.org/groups/2366342/items/RX579NY3/file?page=3" TEXT="ID: adad74601feaa6a2a742f9361c7bfddb &lt;br/&gt; RO(1): to identify game elements used in gamification?  &lt;br/&gt;&lt;br/&gt;Article Title: Gamifying information systems - A synthesis of gamification mechanics and dynamics"/>
    <node LINK="http://zotero.org/groups/2366342/items/CWIJWKDI/file?page=3" TEXT="ID: 152d26e5dfe24bf194fff2740d0f41d8 &lt;br/&gt; RO(1): to identify the implementations of game-based learning related to building services engineering education.  &lt;br/&gt;&lt;br/&gt;Article Title: An overview of game-based learning in building services engineering education"/>
    <node LINK="http://zotero.org/groups/2366342/items/BEGGW57J/file?page=3" TEXT="ID: 9df743d0a224044cbdcdb026bc87dac5 &lt;br/&gt; RO(2): to identify the elements of game mechanics discussed in gamification for health studies  &lt;br/&gt;&lt;br/&gt;Article Title: Health Care Gamification: A Study of Game Mechanics and Elements"/>
    <node LINK="http://zotero.org/groups/2366342/items/RWNJBNWN/file?page=1" TEXT="ID: e43495f4134affff3d9ab46e080ab9a8 &lt;br/&gt; RO(1): to discuss which elements of the game have been used most in gamification learning and the impact of applying gamification learning to students  &lt;br/&gt;&lt;br/&gt;Article Title: The elements of gamification learning in higher education: A systematic literature review"/>
  </node>
</map>
