<?xml version="1.0" encoding="UTF-8"?>
<map version="1.1.0">
  <node TEXT="Without classification">
    <node LINK="http://zotero.org/groups/2366342/items/FXL69DGN/file?page=2" TEXT="ID: 748b7af3bfd9311fd1dd9714f1b9134d &lt;br/&gt; RQ(2): What dynamics, mechanics, and components are used the most in MOOCs?  &lt;br/&gt;&lt;br/&gt;Article Title: Engaging MOOC through gamification: Systematic mapping review"/>
    <node LINK="http://zotero.org/groups/2366342/items/FXL69DGN/file?page=2" TEXT="ID: be334c1e593eb08be48f2bb8c928c9df &lt;br/&gt; RQ(1): How gamification was applied to MOOCs?  &lt;br/&gt;&lt;br/&gt;Article Title: Engaging MOOC through gamification: Systematic mapping review"/>
    <node LINK="http://zotero.org/groups/2366342/items/FXL69DGN/file?page=2" TEXT="ID: d5166581e7cfb61c463ffd4e9e0a149c &lt;br/&gt; RQ(3): How the gamification effect in MOOCs was evaluated?  &lt;br/&gt;&lt;br/&gt;Article Title: Engaging MOOC through gamification: Systematic mapping review"/>
    <node LINK="http://zotero.org/groups/2366342/items/6QGS7ZD7/file?page=7" TEXT="ID: e0690d55c502617ae088fc790982f5ac &lt;br/&gt; RQ(2): What was the purpose for using gamification?  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in theory and action: A survey"/>
    <node LINK="http://zotero.org/groups/2366342/items/H5KSNXDS/file?page=2" TEXT="ID: 72332f6311ac333b4357c6807c146ad3 &lt;br/&gt; RQ(1): How many research papers are produced?  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in IoT application: A systematic mapping study"/>
    <node LINK="http://zotero.org/groups/2366342/items/ZRJZK6MC/file?page=2" TEXT="ID: 298c43a39545a17af8190a36b77a9a2f &lt;br/&gt; RQ(1): Which programming concepts are usually overlooked by the researchers?  &lt;br/&gt;&lt;br/&gt;Article Title: A Review of Gamification for Learning Programming Fundamental"/>
    <node LINK="http://zotero.org/groups/2366342/items/TMSX55QH/file?page=12" TEXT="ID: e195c12c218a24dc0c6727c438821026 &lt;br/&gt; RQ(2): Which technological tools can be used to improve learner immersion?  &lt;br/&gt;&lt;br/&gt;Article Title: Approaching Sustainability Learning Via Digital Serious Games"/>
    <node LINK="http://zotero.org/groups/2366342/items/QGNF2RLP/file?page=4" TEXT="ID: ae55a7557a6fd214f0701b74a8335138 &lt;br/&gt; RQ(3): Does effectiveness of gamification depend on school levels? (Primary school, secondary school, high school and university)  &lt;br/&gt;&lt;br/&gt;Article Title: The effects of gamification on students’ academic achievement: a meta-analysis study"/>
    <node LINK="http://zotero.org/groups/2366342/items/AX46XTC8/file?page=5" TEXT="ID: c40832ac4b18fd08751ee1bff6cc4a71 &lt;br/&gt; RQ(1): How do the theories and frameworks from HCI, gaming, and psychology have been applied on gamification? (inferred) &lt;br/&gt;&lt;br/&gt;Article Title: Gamification Framework: The Contribution of User Centered Design, Social Media Applications, Gaming and Psychology Concepts and Frameworks"/>
    <node LINK="http://zotero.org/groups/2366342/items/FXL69DGN/file?page=2" TEXT="ID: 2852706db8571c908ef0f2b0e59e7a3d &lt;br/&gt; RQ(6): Is gamification part of the MOOC's technological environment?  &lt;br/&gt;&lt;br/&gt;Article Title: Engaging MOOC through gamification: Systematic mapping review"/>
    <node LINK="http://zotero.org/groups/2366342/items/TMSX55QH/file?page=12" TEXT="ID: f1bd22f5e4584eea8fa127bfe4dc27b2 &lt;br/&gt; RQ(1): Which methodological frameworks are most suited to drive SSG (motivational games and educational games) design?  &lt;br/&gt;&lt;br/&gt;Article Title: Approaching Sustainability Learning Via Digital Serious Games"/>
    <node LINK="http://zotero.org/groups/2366342/items/SSENW62L/file?page=2" TEXT="ID: ed6b979e2332fef348af90f582c4ced7 &lt;br/&gt; RQ(3): What is the future of the employment of gamification in the era of digital transformation in business organizations?  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in Management: analysis and research directions"/>
    <node LINK="http://zotero.org/groups/2366342/items/SSENW62L/file?page=2" TEXT="ID: e7c828e00b71a41a9c21c4c98b58cb3c &lt;br/&gt; RQ(1): How can gamification be employed as a management strategy in a digital transformation era?  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in Management: analysis and research directions"/>
    <node LINK="http://zotero.org/groups/2366342/items/4TDM3GFC/file?page=2" TEXT="ID: b4c452a231584a638785cffc139af223 &lt;br/&gt; RQ(2): Does the empirical evidence support the use gamification and serious games in the corporate training environment?  &lt;br/&gt;&lt;br/&gt;Article Title: Serious Games and Gamification in the Corporate Training Environment: a Literature Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/EAWY3579/file?page=1" TEXT="ID: c558349aa62a6881969d43fd73caabf8 &lt;br/&gt; RQ(1): How gamification has been applied in e-government?  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in e-Govemment: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/H5KSNXDS/file?page=2" TEXT="ID: aa0cbc66a19d5990b124bd925dafcc18 &lt;br/&gt; RQ(3): How publications are distributed across countries?  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in IoT application: A systematic mapping study"/>
    <node LINK="http://zotero.org/groups/2366342/items/U78FKG67/file?page=8" TEXT="ID: 314eee287961968191b14664f1803f8a &lt;br/&gt; RQ(3): In which publication journals are the 25 most cited articles on gamification in education published? (inferred) &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in management education - A literature mapping"/>
    <node LINK="http://zotero.org/groups/2366342/items/U78FKG67/file?page=8" TEXT="ID: 3d963c5f1c0b8ef383e93c84bfd2a33e &lt;br/&gt; RQ(4): Which universities published the 25 most cited articles of gamification in education? (inferred) &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in management education - A literature mapping"/>
    <node LINK="http://zotero.org/groups/2366342/items/PHKXE7KX/file?page=2" TEXT="ID: 908140d16bd3b487dc68308cfe7dd38d &lt;br/&gt; RQ(4): What are the possible gamification techniques for application directed to the Engineering teaching?  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification as a strategy to improve students’ motivation and engagement in educational environments at engineering courses: bibliographic"/>
    <node LINK="http://zotero.org/groups/2366342/items/H5KSNXDS/file?page=2" TEXT="ID: 0b0d73fe96e2f94836b884f128e0de54 &lt;br/&gt; RQ(5): In which areas is gamification applied to IoT applications?  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in IoT application: A systematic mapping study"/>
    <node LINK="http://zotero.org/groups/2366342/items/ZHZEUC5A/file?page=3" TEXT="ID: 4f35f139efb5880c710c92feec1e9b7a &lt;br/&gt; RQ(1): In which application has gamification been applied? (inferred) &lt;br/&gt;&lt;br/&gt;Article Title: Review of benefit using gamification element for countryside tourism"/>
    <node LINK="http://zotero.org/groups/2366342/items/BLJXTZCY/file?page=3" TEXT="ID: 9bec803b9afdb7e548d6bd8f0356021c &lt;br/&gt; RQ(1): What is/are the learning objectives?  &lt;br/&gt;&lt;br/&gt;Article Title: Designing Gamified Interventions for Autism Spectrum Disorder: A Systematic Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/BLJXTZCY/file?page=3" TEXT="ID: 0894b20e53a4c987716cb48d37a7e7f1 &lt;br/&gt; RQ(3): Who is the target audience?  &lt;br/&gt;&lt;br/&gt;Article Title: Designing Gamified Interventions for Autism Spectrum Disorder: A Systematic Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/H5KSNXDS/file?page=2" TEXT="ID: 398ff4c3af78328fd1108e1cb0ae348a &lt;br/&gt; RQ(6): What are the most frequently obtained artefacts?  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in IoT application: A systematic mapping study"/>
    <node LINK="http://zotero.org/groups/2366342/items/CFNJMTG7/file?page=3" TEXT="ID: c834c8b4dd7dffe640993841b2c0ea0b &lt;br/&gt; RQ(7): What is the number of publications by year?  &lt;br/&gt;&lt;br/&gt;Article Title: A systematic mapping study on gamification applied to e-marketing"/>
    <node LINK="http://zotero.org/groups/2366342/items/H5KSNXDS/file?page=2" TEXT="ID: 740a724411a4d68cc1fbc58fc9eb0ecd &lt;br/&gt; RQ(2): What is the annual trend of publications?  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in IoT application: A systematic mapping study"/>
    <node LINK="http://zotero.org/groups/2366342/items/H5KSNXDS/file?page=2" TEXT="ID: fd42d0e9713a3c8858c4a05990bca030 &lt;br/&gt; RQ(4): What is the quality of relevant articles according to Conference and / or Journal rank?  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in IoT application: A systematic mapping study"/>
    <node LINK="http://zotero.org/groups/2366342/items/ZHZEUC5A/file?page=4" TEXT="ID: f5919ef43bc0038090cd203d413fb34d &lt;br/&gt; RQ(3): What are the impact of gamification fortourism? (inferred) &lt;br/&gt;&lt;br/&gt;Article Title: Review of benefit using gamification element for countryside tourism"/>
    <node LINK="http://zotero.org/groups/2366342/items/U78FKG67/file?page=5" TEXT="ID: cb556de69f79d66d2344cb7f5dc7437b &lt;br/&gt; RQ(1): What are the 25 most cited articles on gamification and their authors ? (inferred) &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in management education - A literature mapping"/>
    <node LINK="http://zotero.org/groups/2366342/items/U78FKG67/file?page=6" TEXT="ID: 2e317ee16713f9e953bf7c3219ac6171 &lt;br/&gt; RQ(2): What are the countries of the 25 most cited articles on gamification in education? (inferred) &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in management education - A literature mapping"/>
    <node LINK="http://zotero.org/groups/2366342/items/IHLIL5I5/file?page=6" TEXT="ID: 49749e4755d99f93583c07b9556b0fd5 &lt;br/&gt; RQ(1): What are the publication, in terms of nature of the study, duration, number of participants,and statistical information, related to the gamification of LESL? (inferred) &lt;br/&gt;&lt;br/&gt;Article Title: Using gamification to support learning English as a second language: a systematic review"/>
    <node LINK="http://zotero.org/groups/2366342/items/ZRJZK6MC/file?page=2" TEXT="ID: 8ed86c0160f29bec69f872d8a4918748 &lt;br/&gt; RQ(2): What Game Elements should be included that ensures active participation of students?  &lt;br/&gt;&lt;br/&gt;Article Title: A Review of Gamification for Learning Programming Fundamental"/>
    <node LINK="http://zotero.org/groups/2366342/items/4JKM5VGU/file?page=6" TEXT="ID: 7624ed5f7127a142e98c5f60ae698708 &lt;br/&gt; RQ(1): What were the substantive features of the included studies, such as publication information, instructional context, and learners' background?  &lt;br/&gt;&lt;br/&gt;Article Title: A scoping review of digital game-based technology on English language learning"/>
    <node LINK="http://zotero.org/groups/2366342/items/TSBLY85U/file?page=2" TEXT="ID: 4f605082d03d9cb1a385dd67f7d2ce71 &lt;br/&gt; RQ(1): What are the current kinds of contributions to the eld of adaptive gamicafition in education?  &lt;br/&gt;&lt;br/&gt;Article Title: Adaptive Gamification in Education: A Literature Review of Current Trends and Developments"/>
    <node LINK="http://zotero.org/groups/2366342/items/PHKXE7KX/file?page=2" TEXT="ID: 319a9a3e5741473ac52be98520f47356 &lt;br/&gt; RQ(1): Can the application of gamification techniques contribute to student engagement and motivation?   &lt;br/&gt;&lt;br/&gt;Article Title: Gamification as a strategy to improve students’ motivation and engagement in educational environments at engineering courses: bibliographic"/>
    <node LINK="http://zotero.org/groups/2366342/items/U78FKG67/file?page=9" TEXT="ID: 60f4221d92cf76264c4f65136b21f2a1 &lt;br/&gt; RQ(5): What are the type of studies, objectives and conclusions for the 25 most cited articles of gamification in education? (inferred) &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in management education - A literature mapping"/>
    <node LINK="http://zotero.org/groups/2366342/items/U78FKG67/file?page=13" TEXT="ID: 5df3783fd641b113d626c27dd9e70dde &lt;br/&gt; RQ(7): What are the objectives, study type, and conclusions on the most 14 cited articles of gamification in management education? (inferred) &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in management education - A literature mapping"/>
    <node LINK="http://zotero.org/groups/2366342/items/QGNF2RLP/file?page=4" TEXT="ID: 2ef64b4ce626f02aba2a15d25d74e6f4 &lt;br/&gt; RQ(1): What is the effectiveness of gamification for promoting student academic achievement?  &lt;br/&gt;&lt;br/&gt;Article Title: The effects of gamification on students’ academic achievement: a meta-analysis study"/>
    <node LINK="http://zotero.org/groups/2366342/items/24JK4VEG/file?page=2" TEXT="ID: 6407244b9df9f44f136960e6cfdfbb37 &lt;br/&gt; RQ(1): What are the gamified apps used in CPR training?  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in CPR - A Review of Game Dynamics and Mechanics"/>
    <node LINK="http://zotero.org/groups/2366342/items/CFNJMTG7/file?page=3" TEXT="ID: e762a3ca366662f08c2fe3e8595ce96c &lt;br/&gt; RQ(1): What is the main research areas of applying gamification in e-marketing?  &lt;br/&gt;&lt;br/&gt;Article Title: A systematic mapping study on gamification applied to e-marketing"/>
    <node LINK="http://zotero.org/groups/2366342/items/CFNJMTG7/file?page=3" TEXT="ID: 6b3b95feecd0a62f13cca416bdcac72a &lt;br/&gt; RQ(5): Is it possible to classify the studies in this area in a special way?  &lt;br/&gt;&lt;br/&gt;Article Title: A systematic mapping study on gamification applied to e-marketing"/>
    <node LINK="http://zotero.org/groups/2366342/items/ADG26DDQ/file?page=3" TEXT="ID: 8109e0b68aabd82d80890bd10151877e &lt;br/&gt; RQ(2): How should gamification principles be deployed in enterprise gamification systems?  &lt;br/&gt;&lt;br/&gt;Article Title: Enterprise gamification systems and employment legislation: a systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/2IH7Y8RH/file?page=1" TEXT="ID: 7d2701c0fe597ddb9677cfa1493407d3 &lt;br/&gt; RQ(1): Is there a classification for serious games, gamified applications and educational software?  &lt;br/&gt;&lt;br/&gt;Article Title: Serious game, gamified applications, educational software: A comparative study"/>
    <node LINK="http://zotero.org/groups/2366342/items/2IH7Y8RH/file?page=1" TEXT="ID: 0a552b490ab3af76b2cc0f18d1ba0fa0 &lt;br/&gt; RQ(2): What are the application domains that encompass serious games, gamified applications and educational software?  &lt;br/&gt;&lt;br/&gt;Article Title: Serious game, gamified applications, educational software: A comparative study"/>
    <node LINK="http://zotero.org/groups/2366342/items/SYLN3YZV/file?page=2" TEXT="ID: dd7496ae67396becb5726bfbb4536d9b &lt;br/&gt; RQ(3): What are frameworks used in adaptive gamification?  &lt;br/&gt;&lt;br/&gt;Article Title: A systematic literature review on adaptive gamification: Components, methods, and frameworks"/>
    <node LINK="http://zotero.org/groups/2366342/items/34H9ZFI6/file?page=3" TEXT="ID: 42c9b92886f4239bc5ca18e41b1d1613 &lt;br/&gt; RQ(1): What are the gamification frameworks for e-learning platforms? (inferred) &lt;br/&gt;&lt;br/&gt;Article Title: A Gamification Model for E-Learning Platforms"/>
    <node LINK="http://zotero.org/groups/2366342/items/MV3ESRRI/file?page=2" TEXT="ID: 426a9e4e7dec88c6767ed2980adbdcfa &lt;br/&gt; RQ(3): What learning outcomes from problem-based learning using gamification?  &lt;br/&gt;&lt;br/&gt;Article Title: Problem based learning using gamification: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/4JKM5VGU/file?page=6" TEXT="ID: 6876b078ebc32fc62fa8893448b074aa &lt;br/&gt; RQ(3): Which language learning skills were targeted using DGBLL (listening, speaking, reading, writing, vocabulary, grammar, and pragmatic competence)?  &lt;br/&gt;&lt;br/&gt;Article Title: A scoping review of digital game-based technology on English language learning"/>
    <node LINK="http://zotero.org/groups/2366342/items/SYLN3YZV/file?page=2" TEXT="ID: 69227927976ab08de4756d60b66ca57d &lt;br/&gt; RQ(1): What are components used in adaptive gamification?  &lt;br/&gt;&lt;br/&gt;Article Title: A systematic literature review on adaptive gamification: Components, methods, and frameworks"/>
    <node LINK="http://zotero.org/groups/2366342/items/SYLN3YZV/file?page=2" TEXT="ID: 093ed9d794d658c54ce64e507c2445d1 &lt;br/&gt; RQ(2): What are methods used in adaptive gamification?  &lt;br/&gt;&lt;br/&gt;Article Title: A systematic literature review on adaptive gamification: Components, methods, and frameworks"/>
    <node LINK="http://zotero.org/groups/2366342/items/TSBLY85U/file?page=2" TEXT="ID: 5c1097c31a07f4045f9fb7a7ea85ecdb &lt;br/&gt; RQ(3): What is the impact of the adaptive gamification and how is this impact measured?  &lt;br/&gt;&lt;br/&gt;Article Title: Adaptive Gamification in Education: A Literature Review of Current Trends and Developments"/>
    <node LINK="http://zotero.org/groups/2366342/items/ZHZEUC5A/file?page=3" TEXT="ID: 3b9234827db76ee02786d6f8c13492e4 &lt;br/&gt; RQ(2): What are the impact of gamification for managers of tourism sites? (inferred) &lt;br/&gt;&lt;br/&gt;Article Title: Review of benefit using gamification element for countryside tourism"/>
    <node LINK="http://zotero.org/groups/2366342/items/SSENW62L/file?page=2" TEXT="ID: de1e1cd013de1e6820aa13b327be29fd &lt;br/&gt; RQ(2): What is the main purpose for the employment of gamification in management contexts?  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in Management: analysis and research directions"/>
    <node LINK="http://zotero.org/groups/2366342/items/CFNJMTG7/file?page=3" TEXT="ID: 38fdc2a9e353849e0b60f1f79dd5b959 &lt;br/&gt; RQ(3): What technologies are employed by researchers to implement gamification in e-marketing?  &lt;br/&gt;&lt;br/&gt;Article Title: A systematic mapping study on gamification applied to e-marketing"/>
    <node LINK="http://zotero.org/groups/2366342/items/UDM6MNDX/file?page=3" TEXT="ID: f07676cb2ae183926ff157906da72490 &lt;br/&gt; RQ(3): What reasons do researchers give for applying gamification to apps and technologies for improving mental health and well-being?  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in apps and technologies for improving mental health and well-being: Systematic review"/>
    <node LINK="http://zotero.org/groups/2366342/items/UDM6MNDX/file?page=3" TEXT="ID: 38ba4e3557e9c901813b5e94a1a06c37 &lt;br/&gt; RQ(1): Which gamification elements are most commonly applied to apps and technologies for improving mental health and well-being?  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in apps and technologies for improving mental health and well-being: Systematic review"/>
    <node LINK="http://zotero.org/groups/2366342/items/UDM6MNDX/file?page=3" TEXT="ID: 9051d3896fa983ce0d16f36d011d73ee &lt;br/&gt; RQ(2): Which mental health and well-being domains are most commonly targeted by these gamified apps and technologies?  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in apps and technologies for improving mental health and well-being: Systematic review"/>
    <node LINK="http://zotero.org/groups/2366342/items/4JKM5VGU/file?page=6" TEXT="ID: 26a804e76e7680d3ca6e6f91ba844d87 &lt;br/&gt; RQ(6): What pedagogical role did DBGLL serve in the instruction of ELLs?  &lt;br/&gt;&lt;br/&gt;Article Title: A scoping review of digital game-based technology on English language learning"/>
    <node LINK="http://zotero.org/groups/2366342/items/4JKM5VGU/file?page=6" TEXT="ID: 01cf6a65d4f5ff223c7bbaa21dcd4dfb &lt;br/&gt; RQ(4): What is the impact of DGBLL on English language learners' (ELLs') learning outcomes?  &lt;br/&gt;&lt;br/&gt;Article Title: A scoping review of digital game-based technology on English language learning"/>
    <node LINK="http://zotero.org/groups/2366342/items/4TDM3GFC/file?page=2" TEXT="ID: 95ebf56dd626042e9279390d9ea22069 &lt;br/&gt; RQ(3): What are the demographic and cultural influences on the successes of gamification in the workplace?  &lt;br/&gt;&lt;br/&gt;Article Title: Serious Games and Gamification in the Corporate Training Environment: a Literature Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/4TDM3GFC/file?page=2" TEXT="ID: e895c72dde392d6133f89f372486886f &lt;br/&gt; RQ(1): What are the strategies of gamification and serious games being applied in the corporate training context?  &lt;br/&gt;&lt;br/&gt;Article Title: Serious Games and Gamification in the Corporate Training Environment: a Literature Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/ADG26DDQ/file?page=3" TEXT="ID: 95cec0114bc63cef8df194487d830b77 &lt;br/&gt; RQ(1): Given that enterprise gamification systems change the employer-employee relationship, are there any legal considerations that gamification system designers must take into account?  &lt;br/&gt;&lt;br/&gt;Article Title: Enterprise gamification systems and employment legislation: a systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/BLJXTZCY/file?page=3" TEXT="ID: 0ee7ef59b5428ee0cca324f33f33fea5 &lt;br/&gt; RQ(5): What representation methods are applied in the User Interface design?  &lt;br/&gt;&lt;br/&gt;Article Title: Designing Gamified Interventions for Autism Spectrum Disorder: A Systematic Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/IHLIL5I5/file?page=12" TEXT="ID: ea2d16c0ba2f81802cf36f2174283c9f &lt;br/&gt; RQ(3): What are the learners experiences explored in the gamification of LESL? (inferred) &lt;br/&gt;&lt;br/&gt;Article Title: Using gamification to support learning English as a second language: a systematic review"/>
    <node LINK="http://zotero.org/groups/2366342/items/IHLIL5I5/file?page=13" TEXT="ID: 048e4faff4bc89e153a3b09afe1e1291 &lt;br/&gt; RQ(4): What are the learners outcomes explored in the gamification of LESL? (inferred) &lt;br/&gt;&lt;br/&gt;Article Title: Using gamification to support learning English as a second language: a systematic review"/>
    <node LINK="http://zotero.org/groups/2366342/items/QGNF2RLP/file?page=4" TEXT="ID: c3b05593118f110d6e92090fe5c0b1fc &lt;br/&gt; RQ(2): Does effectiveness of gamification depend on the course type? (Technology class or non-technology class)  &lt;br/&gt;&lt;br/&gt;Article Title: The effects of gamification on students’ academic achievement: a meta-analysis study"/>
    <node LINK="http://zotero.org/groups/2366342/items/TMSX55QH/file?page=13" TEXT="ID: 36e3ba6c037b7560dd4e124f748d8722 &lt;br/&gt; RQ(3): Since interaction among various players is a relevant factor in sustainability learning, which design elements and tools can foster cooperative/competitive behaviors?  &lt;br/&gt;&lt;br/&gt;Article Title: Approaching Sustainability Learning Via Digital Serious Games"/>
    <node LINK="http://zotero.org/groups/2366342/items/PHKXE7KX/file?page=2" TEXT="ID: 44500a1f6854ae47302d8692b3e8a351 &lt;br/&gt; RQ(3): Does the use of gamification contribute to the learning process related to Engineering courses?  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification as a strategy to improve students’ motivation and engagement in educational environments at engineering courses: bibliographic"/>
    <node LINK="http://zotero.org/groups/2366342/items/MV3ESRRI/file?page=2" TEXT="ID: 9e435a79f031e52de847f4264717af6b &lt;br/&gt; RQ(1): What affordances are used to supports gamification solution on problem based learning?  &lt;br/&gt;&lt;br/&gt;Article Title: Problem based learning using gamification: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/MV3ESRRI/file?page=2" TEXT="ID: 69007063d193d4422950edfc852746c8 &lt;br/&gt; RQ(2): What technology needed to supports problem-based learning using gamification?  &lt;br/&gt;&lt;br/&gt;Article Title: Problem based learning using gamification: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/FXL69DGN/file?page=2" TEXT="ID: 26ee4ae4e3b84f53265dea12e6a08a1d &lt;br/&gt; RQ(4): What are the most important results?  &lt;br/&gt;&lt;br/&gt;Article Title: Engaging MOOC through gamification: Systematic mapping review"/>
    <node LINK="http://zotero.org/groups/2366342/items/BLJXTZCY/file?page=3" TEXT="ID: b985f0ed0aeed3e10fa18b3f4181d09c &lt;br/&gt; RQ(2): What is the development process/methodology/approach employed?  &lt;br/&gt;&lt;br/&gt;Article Title: Designing Gamified Interventions for Autism Spectrum Disorder: A Systematic Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/4JKM5VGU/file?page=6" TEXT="ID: 8e204aee2b3fffbc860961863e52aa5e &lt;br/&gt; RQ(2): What were the methodological features of the included studies, such as the research methods employed, data collection approaches, and sample size?  &lt;br/&gt;&lt;br/&gt;Article Title: A scoping review of digital game-based technology on English language learning"/>
    <node LINK="http://zotero.org/groups/2366342/items/CFNJMTG7/file?page=3" TEXT="ID: d690033195a3e80927e90a110da97652 &lt;br/&gt; RQ(6): Where has the research been published?  &lt;br/&gt;&lt;br/&gt;Article Title: A systematic mapping study on gamification applied to e-marketing"/>
    <node LINK="http://zotero.org/groups/2366342/items/FXL69DGN/file?page=2" TEXT="ID: 481be00b81e561dd60dfd5f21b9af1ed &lt;br/&gt; RQ(5): What MOOC type was used?  &lt;br/&gt;&lt;br/&gt;Article Title: Engaging MOOC through gamification: Systematic mapping review"/>
    <node LINK="http://zotero.org/groups/2366342/items/ZRJZK6MC/file?page=2" TEXT="ID: 1efa0012b05aba53eb729bcd48be653d &lt;br/&gt; RQ(3): What evaluation methods are used to measure the effectiveness of gamification?  &lt;br/&gt;&lt;br/&gt;Article Title: A Review of Gamification for Learning Programming Fundamental"/>
    <node LINK="http://zotero.org/groups/2366342/items/CFNJMTG7/file?page=3" TEXT="ID: ee69a7eab86533db5357ea4da31807e8 &lt;br/&gt; RQ(2): What are the benefits of using gamification in e-marketing?  &lt;br/&gt;&lt;br/&gt;Article Title: A systematic mapping study on gamification applied to e-marketing"/>
    <node LINK="http://zotero.org/groups/2366342/items/GZPP6FJE/file?page=1" TEXT="ID: c91d66c54dc64408fb583bffe8d93fe4 &lt;br/&gt; RQ(2): Why have researchers opted to use gamification?  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification of Cognitive Assessment and Cognitive Training: A Systematic Review of Applications and Efficacy"/>
    <node LINK="http://zotero.org/groups/2366342/items/EAWY3579/file?page=1" TEXT="ID: 622cc150006e5209f17fbbbf5ed3108f &lt;br/&gt; RQ(3): What rewarding schemes do fit best?  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in e-Govemment: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/KPSZJH37/file?page=5" TEXT="ID: f3fce3b76327e397029037ab1458d06b &lt;br/&gt; RQ(4): What are the characteristics of theoretical research about gamification in the workplace? (inferred) &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in the workplace: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/2IH7Y8RH/file?page=1" TEXT="ID: 87d67dba8c0fbf30bd5e817bc87e54e0 &lt;br/&gt; RQ(4): What characteristics do they share and how do serious games differ from gamified applications and educational software?  &lt;br/&gt;&lt;br/&gt;Article Title: Serious game, gamified applications, educational software: A comparative study"/>
    <node LINK="http://zotero.org/groups/2366342/items/2IH7Y8RH/file?page=1" TEXT="ID: 489e7595009c6a9963e4b73251897db6 &lt;br/&gt; RQ(3): What elements characterize serious games, gamified applications and educational software?  &lt;br/&gt;&lt;br/&gt;Article Title: Serious game, gamified applications, educational software: A comparative study"/>
    <node LINK="http://zotero.org/groups/2366342/items/TSBLY85U/file?page=2" TEXT="ID: fbeace4db849df45ea674d8322ed0b8a &lt;br/&gt; RQ(2): What do the current contributions base their adaptation on, and what is the effect of this adaptation on the gamified system?  &lt;br/&gt;&lt;br/&gt;Article Title: Adaptive Gamification in Education: A Literature Review of Current Trends and Developments"/>
    <node LINK="http://zotero.org/groups/2366342/items/AQG63SCH/file?page=6" TEXT="ID: 785710f926ed81d21dec7c02e4bffe3b &lt;br/&gt; RQ(3): What are the current studies on game-based learning in higher education? (inferred) &lt;br/&gt;&lt;br/&gt;Article Title: Gamified learning in higher education: A systematic review of the literature"/>
    <node LINK="http://zotero.org/groups/2366342/items/ERBZ46ZZ/file?page=1" TEXT="ID: 1cc2c57bb1786e57c2dc4fac359da1b6 &lt;br/&gt; RQ(1): What guidelines may provide to future research, the key themes and concepts found in published scientific papers on gamification?  &lt;br/&gt;&lt;br/&gt;Article Title: Main gamification concepts: A systematic mapping study"/>
    <node LINK="http://zotero.org/groups/2366342/items/4TDM3GFC/file?page=2" TEXT="ID: 60b6d1ba1c61e4662c5f76a5094acb6d &lt;br/&gt; RQ(4): What are the ethical issues, challenges, and constraints of serious games and gamification in the corporate environment?  &lt;br/&gt;&lt;br/&gt;Article Title: Serious Games and Gamification in the Corporate Training Environment: a Literature Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/RY2DM4V4/file?page=2" TEXT="ID: c2ffb657ff35d7534fde95cfb76d6676 &lt;br/&gt; RQ(1): What does the literature have to say about applying gamification in businesses through ERP systems as a means to creating an innovative environment?  &lt;br/&gt;&lt;br/&gt;Article Title: The Hero's Journey to Innovation: Gamification in Enterprise Systems"/>
    <node LINK="http://zotero.org/groups/2366342/items/3PIVJ6GK/file?page=3" TEXT="ID: 4769d482770e11bbfe4ae39c56319399 &lt;br/&gt; RQ(1): What software engineering processes have been the object of gamification?  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in software engineering - A systematic mapping"/>
    <node LINK="http://zotero.org/groups/2366342/items/CYHRUKLX/file?page=2" TEXT="ID: 3b8bd8a8f5f6929d14005c7791961223 &lt;br/&gt; RQ(3): What factors need to be considered for designing effective gamification of online learning environments, specifically MOOCs?  &lt;br/&gt;&lt;br/&gt;Article Title: The effects of gamification in online learning environments: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/CYHRUKLX/file?page=2" TEXT="ID: 0427b2f85814d8d2bc69ead5787b42f8 &lt;br/&gt; RQ(1): What are the gamification elements mostly used in online learning environments?  &lt;br/&gt;&lt;br/&gt;Article Title: The effects of gamification in online learning environments: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/34H9ZFI6/file?page=5" TEXT="ID: 08edaed88fbb266b9250656f019b8e81 &lt;br/&gt; RQ(2): What are the design elements and constructs in gamification design framework for an e-learning platform? (inferred) &lt;br/&gt;&lt;br/&gt;Article Title: A Gamification Model for E-Learning Platforms"/>
    <node LINK="http://zotero.org/groups/2366342/items/R76JUB22/file?page=8" TEXT="ID: dcfdfcba7b8e4bf97de9926dd7536350 &lt;br/&gt; RQ(5): What are the factors studied concurrently on the gamification of learning for the engineering context? (inferred) &lt;br/&gt;&lt;br/&gt;Article Title: Systematic literature review: An exploration of gamification in the context of engineering education"/>
    <node LINK="http://zotero.org/groups/2366342/items/EAWY3579/file?page=1" TEXT="ID: 409ebbccf92d3bd7f46a836fadadf909 &lt;br/&gt; RQ(4): How successful has been the gamification in its implementation?  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in e-Govemment: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/22XCUTKU/file?page=3" TEXT="ID: 193b42b4c61d2765a3d6dabcdc99574f &lt;br/&gt; RQ(1): How can gamification elements/techniques be used to promote students' learning?  &lt;br/&gt;&lt;br/&gt;Article Title: The Role of Gamification Techniques in Promoting Student Learning: A Review and Synthesis"/>
    <node LINK="http://zotero.org/groups/2366342/items/PHKXE7KX/file?page=2" TEXT="ID: 71c3026bdc9fa70f827d0ddf1e30ca77 &lt;br/&gt; RQ(2): What examples of gamification techniques in learning environments can be found?  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification as a strategy to improve students’ motivation and engagement in educational environments at engineering courses: bibliographic"/>
    <node LINK="http://zotero.org/groups/2366342/items/CYHRUKLX/file?page=2" TEXT="ID: f96fcdcbce3405519532c08065d41504 &lt;br/&gt; RQ(2): What are the effects of these game elements on learners' behaviour in online learning environments?  &lt;br/&gt;&lt;br/&gt;Article Title: The effects of gamification in online learning environments: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/24JK4VEG/file?page=3" TEXT="ID: 13bf3ffc7de59d0edc0ea0eb92acbb49 &lt;br/&gt; RQ(2): In which CPR training elements are the gamified elements applied? (inferred) &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in CPR - A Review of Game Dynamics and Mechanics"/>
    <node LINK="http://zotero.org/groups/2366342/items/24JK4VEG/file?page=3" TEXT="ID: 43f18893e4899bd56f0047a7dd63d084 &lt;br/&gt; RQ(3): What game design elements are applied on CPR training? (inferred) &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in CPR - A Review of Game Dynamics and Mechanics"/>
    <node LINK="http://zotero.org/groups/2366342/items/4JKM5VGU/file?page=6" TEXT="ID: 91a8a4dcab7a84774abfca36f0faea27 &lt;br/&gt; RQ(5): What game elements were implemented to support ELLs?  &lt;br/&gt;&lt;br/&gt;Article Title: A scoping review of digital game-based technology on English language learning"/>
    <node LINK="http://zotero.org/groups/2366342/items/22XCUTKU/file?page=3" TEXT="ID: eb65993737dc4cd7b0740fb25f4d6c45 &lt;br/&gt; RQ(2): What are the challenges in implementing them in a university context?  &lt;br/&gt;&lt;br/&gt;Article Title: The Role of Gamification Techniques in Promoting Student Learning: A Review and Synthesis"/>
    <node LINK="http://zotero.org/groups/2366342/items/EAWY3579/file?page=1" TEXT="ID: 0c25e1bc491d735d32479d7a20cec6f1 &lt;br/&gt; RQ(2): What countries have implemented it?  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in e-Govemment: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/CFNJMTG7/file?page=3" TEXT="ID: 35fe71058860a180a616c36165b5cfa4 &lt;br/&gt; RQ(4): What common themes of recommendations are given by studies?  &lt;br/&gt;&lt;br/&gt;Article Title: A systematic mapping study on gamification applied to e-marketing"/>
    <node LINK="http://zotero.org/groups/2366342/items/BLJXTZCY/file?page=3" TEXT="ID: ef6246775e283be0b8d542168063ac5e &lt;br/&gt; RQ(4): What gamification elements are used to improve learning skills?  &lt;br/&gt;&lt;br/&gt;Article Title: Designing Gamified Interventions for Autism Spectrum Disorder: A Systematic Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/IHLIL5I5/file?page=12" TEXT="ID: 336d4bd5a585629f17755156c6584e2f &lt;br/&gt; RQ(2): What are the gamification elements used in the gamification of LESL? (inferred) &lt;br/&gt;&lt;br/&gt;Article Title: Using gamification to support learning English as a second language: a systematic review"/>
    <node LINK="http://zotero.org/groups/2366342/items/U78FKG67/file?page=13" TEXT="ID: 02cb9c8fb937c4ddd04e8180b312c0be &lt;br/&gt; RQ(6): What are the gamified apps and their game elements on the 25 most cited articles of gamification in education? (inferred) &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in management education - A literature mapping"/>
    <node LINK="http://zotero.org/groups/2366342/items/U78FKG67/file?page=19" TEXT="ID: d8cc7d4978307a7e3b0f499056b8d446 &lt;br/&gt; RQ(8): What are the game apps and their game elements on the most 14 cited articles of gamification in management education?  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in management education - A literature mapping"/>
  </node>
</map>
