<?xml version="1.0" encoding="UTF-8"?>
<map version="1.1.0">
  <node TEXT="Without classification">
    <node LINK="http://zotero.org/groups/2366342/items/IHLIL5I5/file?page=4" TEXT="ID: 213dcc89524ffaadadc36bb6f9cd410e &lt;br/&gt; RO(1): to present an overview of the current state of the art of the literature on gamification for LESL  &lt;br/&gt;&lt;br/&gt;Article Title: Using gamification to support learning English as a second language: a systematic review"/>
    <node LINK="http://zotero.org/groups/2366342/items/TMSX55QH/file?page=2" TEXT="ID: 685552e53973daacc4b3f84e4ea129ee &lt;br/&gt; RO(3): to summarize research questions that may be approached by further research in the field  &lt;br/&gt;&lt;br/&gt;Article Title: Approaching Sustainability Learning Via Digital Serious Games"/>
    <node LINK="http://zotero.org/groups/2366342/items/5FHYJFR3/file?page=3" TEXT="ID: be5bbd7bb7c47758f881801faf866d13 &lt;br/&gt; RO(1): to show what current IS research in high ranked outlets discusses regarding Gamification as a basis for future research activities and as a knowledgebase  &lt;br/&gt;&lt;br/&gt;Article Title: A descriptive literature review and classification framework for Gamification in information systems"/>
    <node LINK="http://zotero.org/groups/2366342/items/CYHRUKLX/file?page=1" TEXT="ID: d865376a5b1c40d66b3d9fd48b1a0b57 &lt;br/&gt; RO(1): to clarify what effects gamification generates on users' behaviors in MOOC  &lt;br/&gt;&lt;br/&gt;Article Title: The effects of gamification in online learning environments: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/SYLN3YZV/file?page=2" TEXT="ID: 7c1aa46f2e146f8542a8c6d46235e086 &lt;br/&gt; RO(3): To identify the frameworks used adaptive gamification  &lt;br/&gt;&lt;br/&gt;Article Title: A systematic literature review on adaptive gamification: Components, methods, and frameworks"/>
    <node LINK="http://zotero.org/groups/2366342/items/ADG26DDQ/file?page=2" TEXT="ID: c910a682d2059e43113dd320105ee283 &lt;br/&gt; RO(1): to explore how game-like structures can make employee to performance management more effective and what their implications are in workplaces  &lt;br/&gt;&lt;br/&gt;Article Title: Enterprise gamification systems and employment legislation: a systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/MV3ESRRI/file?page=2" TEXT="ID: 989bed9cb70da3db08e01a44c2d58c7b &lt;br/&gt; RO(1): To identify affordances that supported gamification solution on problem based learning  &lt;br/&gt;&lt;br/&gt;Article Title: Problem based learning using gamification: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/TMSX55QH/file?page=2" TEXT="ID: 49cb85eb9ec658b79722f606f07556e0 &lt;br/&gt; RO(1): to detail the current state of the art of the various forms of digital gaming approaches to sustainability  &lt;br/&gt;&lt;br/&gt;Article Title: Approaching Sustainability Learning Via Digital Serious Games"/>
    <node LINK="http://zotero.org/groups/2366342/items/IHLIL5I5/file?page=4" TEXT="ID: 9a3af3b724c29f04a4b4e754f16ddb08 &lt;br/&gt; RO(3): to explore learners ' learning experiences (feelings and attitude) and various learning outcomes (content language learning, engagement, motivation, satisfaction) of gamified LESL in digital environments  &lt;br/&gt;&lt;br/&gt;Article Title: Using gamification to support learning English as a second language: a systematic review"/>
    <node LINK="http://zotero.org/groups/2366342/items/SSENW62L/file?page=2" TEXT="ID: 88645bfa6db0675f2c52f1b4852d7b94 &lt;br/&gt; RO(1): this paper analyses and maps the main applications of gamification in management contexts considering its core features, strategies, motivations and purpose  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in Management: analysis and research directions"/>
    <node LINK="http://zotero.org/groups/2366342/items/AAP5YV7B/file?page=2" TEXT="ID: b23c037bb1bf574dcc0978627301070b &lt;br/&gt; RO(2): to consolidate the state of the art of gamification research and rigorously develop a gamification taxonomy  &lt;br/&gt;&lt;br/&gt;Article Title: Is it all about having fun? - Developing a taxonomy to gamify information systems"/>
    <node LINK="http://zotero.org/groups/2366342/items/SYLN3YZV/file?page=2" TEXT="ID: 496a98716796b9e27b3c6480b16433b9 &lt;br/&gt; RO(1): To identify common components to determine adaptive gamification aspects  &lt;br/&gt;&lt;br/&gt;Article Title: A systematic literature review on adaptive gamification: Components, methods, and frameworks"/>
    <node LINK="http://zotero.org/groups/2366342/items/SYLN3YZV/file?page=2" TEXT="ID: 2f1d8b06d158525b4fdd0e2dcc28cfd5 &lt;br/&gt; RO(2): To identify the methods to process component to be adaptive  &lt;br/&gt;&lt;br/&gt;Article Title: A systematic literature review on adaptive gamification: Components, methods, and frameworks"/>
    <node LINK="http://zotero.org/groups/2366342/items/RY2DM4V4/file?page=2" TEXT="ID: 8cc99821fc12c24de3983afeeaf8e220 &lt;br/&gt; RO(1): to explore possibilities of innovation through gamification in ERP systems  &lt;br/&gt;&lt;br/&gt;Article Title: The Hero's Journey to Innovation: Gamification in Enterprise Systems"/>
    <node LINK="http://zotero.org/groups/2366342/items/CFNJMTG7/file?page=1" TEXT="ID: 4078b1d67d61265bb83b8288c1533ef7 &lt;br/&gt; RO(1): to provide a comprehensive overview of the scientific and practical research on gamification applied to e-marketing  &lt;br/&gt;&lt;br/&gt;Article Title: A systematic mapping study on gamification applied to e-marketing"/>
    <node LINK="http://zotero.org/groups/2366342/items/H5KSNXDS/file?page=2" TEXT="ID: 9de936f8b6bc0a9d53e2021d05b297a6 &lt;br/&gt; RO(1): to provide an overview of research articles where gamification joins IoT applications  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in IoT application: A systematic mapping study"/>
    <node LINK="http://zotero.org/groups/2366342/items/MV3ESRRI/file?page=2" TEXT="ID: 96279644fc3086c0e677f0727298f593 &lt;br/&gt; RO(2): To identify the technology needed to develop a problem based learning platform using gamification  &lt;br/&gt;&lt;br/&gt;Article Title: Problem based learning using gamification: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/4TDM3GFC/file?page=2" TEXT="ID: bd48aa1fd1f41cc17539507f945b7a36 &lt;br/&gt; RO(2): to provide concrete examples and contexts for where serious games and gamification have been applied  &lt;br/&gt;&lt;br/&gt;Article Title: Serious Games and Gamification in the Corporate Training Environment: a Literature Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/UDM6MNDX/file?page=3" TEXT="ID: 0d92c61a135a718a64ac09ba4b96c73c &lt;br/&gt; RO(1): to conduct an updated systematic review of the application of gamification in apps and technologies for improving mental health and well-being  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in apps and technologies for improving mental health and well-being: Systematic review"/>
    <node LINK="http://zotero.org/groups/2366342/items/BLJXTZCY/file?page=2" TEXT="ID: 677c84a306a4301acb2bea094ece27d4 &lt;br/&gt; RO(1): to collect data on serious games and/or gami ed interventions for autism, with a focus on the gami cation elements used and their visual representation in terms of the User Interface design  &lt;br/&gt;&lt;br/&gt;Article Title: Designing Gamified Interventions for Autism Spectrum Disorder: A Systematic Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/PHKXE7KX/file?page=1" TEXT="ID: d2e430a4c9b87c0e92581807367105db &lt;br/&gt; RO(1): to identify the perspectives of the use of the concepts and elements geared specifically to Engineering undergraduate programs and courses  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification as a strategy to improve students’ motivation and engagement in educational environments at engineering courses: bibliographic"/>
    <node LINK="http://zotero.org/groups/2366342/items/QGNF2RLP/file?page=4" TEXT="ID: 9abbb94f50e5c80dd99d7c91fdc87bfe &lt;br/&gt; RO(1): to perform a meta-analysis based on gami cation e ects on student achievement  &lt;br/&gt;&lt;br/&gt;Article Title: The effects of gamification on students’ academic achievement: a meta-analysis study"/>
    <node LINK="http://zotero.org/groups/2366342/items/ERBZ46ZZ/file?page=2" TEXT="ID: ee18071590a564a8eca716775f51f219 &lt;br/&gt; RO(1): to identify, analyze and map the emerging concepts and directions in gamification-centered research through qualitative data analysis using Leximancer  &lt;br/&gt;&lt;br/&gt;Article Title: Main gamification concepts: A systematic mapping study"/>
    <node LINK="http://zotero.org/groups/2366342/items/TMSX55QH/file?page=2" TEXT="ID: 2316ba8619df34c56891304b069779f7 &lt;br/&gt; RO(2): to present possible design strategies for sustainability games  &lt;br/&gt;&lt;br/&gt;Article Title: Approaching Sustainability Learning Via Digital Serious Games"/>
    <node LINK="http://zotero.org/groups/2366342/items/22XCUTKU/file?page=2" TEXT="ID: 20a4f912e093499d6bbafab9458f5db9 &lt;br/&gt; RO(1): to determine the role of gamification techniques in promoting students' learning  &lt;br/&gt;&lt;br/&gt;Article Title: The Role of Gamification Techniques in Promoting Student Learning: A Review and Synthesis"/>
    <node LINK="http://zotero.org/groups/2366342/items/34H9ZFI6/file?page=2" TEXT="ID: f867e66c6e18c656f24c3762ba2c347b &lt;br/&gt; RO(2): Identify design elements and constructs for an effective gamified e-learning system  &lt;br/&gt;&lt;br/&gt;Article Title: A Gamification Model for E-Learning Platforms"/>
    <node LINK="http://zotero.org/groups/2366342/items/ZHZEUC5A/file?page=1" TEXT="ID: e1201ddd25659a3973d65b335bdb93be &lt;br/&gt; RO(1): to examine how and what the benefits of using gamification elements are for tourism objects in the countryside, especially for tourist objects in Indonesia  &lt;br/&gt;&lt;br/&gt;Article Title: Review of benefit using gamification element for countryside tourism"/>
    <node LINK="http://zotero.org/groups/2366342/items/MV3ESRRI/file?page=2" TEXT="ID: a39f3bd6a7adc4d14116d8bf5bc337d4 &lt;br/&gt; RO(3): To identify learning outcomes use problem-based learning using gamification  &lt;br/&gt;&lt;br/&gt;Article Title: Problem based learning using gamification: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/IHLIL5I5/file?page=4" TEXT="ID: 21ccc16bfdb374eaa0a6c0dd48d2917e &lt;br/&gt; RO(2): to find out how various gamification elements are used for LESL  &lt;br/&gt;&lt;br/&gt;Article Title: Using gamification to support learning English as a second language: a systematic review"/>
    <node LINK="http://zotero.org/groups/2366342/items/34H9ZFI6/file?page=2" TEXT="ID: 9da555c6c80c8e7a33bb5e6ae315eb94 &lt;br/&gt; RO(3): Propose a gamification design framework for an e-learning platform  &lt;br/&gt;&lt;br/&gt;Article Title: A Gamification Model for E-Learning Platforms"/>
    <node LINK="http://zotero.org/groups/2366342/items/FXL69DGN/file?page=1" TEXT="ID: c45a1b03fc7251118e7b8f0508e2b218 &lt;br/&gt; RO(1): to describe the trend of gamification for education in MOOC within literature  &lt;br/&gt;&lt;br/&gt;Article Title: Engaging MOOC through gamification: Systematic mapping review"/>
    <node LINK="http://zotero.org/groups/2366342/items/2IH7Y8RH/file?page=1" TEXT="ID: 50a3a6319c7f71e0d76d96010b8ff4aa &lt;br/&gt; RO(1): to determinate the differences and similarities in characteristics that exist between serious games, educational software and gamified applications  &lt;br/&gt;&lt;br/&gt;Article Title: Serious game, gamified applications, educational software: A comparative study"/>
    <node LINK="http://zotero.org/groups/2366342/items/ZRJZK6MC/file?page=2" TEXT="ID: c8d9e873f09925f0123a6719d78b525e &lt;br/&gt; RO(1): to identify and analyze the gaps that exist in the literature field of serious programming games  &lt;br/&gt;&lt;br/&gt;Article Title: A Review of Gamification for Learning Programming Fundamental"/>
    <node LINK="http://zotero.org/groups/2366342/items/U78FKG67/file?page=2" TEXT="ID: 94534c776e84cb4b82c57a37dd78740a &lt;br/&gt; RO(2): to explores the results obtained by tested gamification resources and the most significant themes in the field of gamification applications  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in management education - A literature mapping"/>
    <node LINK="http://zotero.org/groups/2366342/items/4TDM3GFC/file?page=2" TEXT="ID: 28072e33068be86a99ac14ad0aa81d45 &lt;br/&gt; RO(1): to provide synthesize research and findings in the corporate training environment including demographics and empirical evidence of success and challenges in the enterprise setting  &lt;br/&gt;&lt;br/&gt;Article Title: Serious Games and Gamification in the Corporate Training Environment: a Literature Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/4TDM3GFC/file?page=2" TEXT="ID: 32f791389815ab3c17d2ade4677df1bc &lt;br/&gt; RO(3): to identify gaps between theory and practice in the corporate training environment  &lt;br/&gt;&lt;br/&gt;Article Title: Serious Games and Gamification in the Corporate Training Environment: a Literature Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/EAWY3579/file?page=1" TEXT="ID: 027ed42a05175cd6687818a3e8636254 &lt;br/&gt; RO(1): To identify the requirements for building a prototype of gamification for e-goverment in Indonesia (inferred) &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in e-Govemment: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/U78FKG67/file?page=2" TEXT="ID: 4ab47896bc5a2bc44773585f15282a97 &lt;br/&gt; RO(1): to identify the patterns prevailing in terms of publications, their authors, citations and coverage by journals  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in management education - A literature mapping"/>
    <node LINK="http://zotero.org/groups/2366342/items/34H9ZFI6/file?page=2" TEXT="ID: b0ff25071121c19610faa19053476a63 &lt;br/&gt; RO(1): Review literature on the gamification frameworks suitable for e-learning platforms  &lt;br/&gt;&lt;br/&gt;Article Title: A Gamification Model for E-Learning Platforms"/>
    <node LINK="http://zotero.org/groups/2366342/items/24JK4VEG/file?page=1" TEXT="ID: ec6aa33216857669bff523d02c088854 &lt;br/&gt; RO(1): to review in the available literature how game-based CPR training software incorporates these elements  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification in CPR - A Review of Game Dynamics and Mechanics"/>
    <node LINK="http://zotero.org/groups/2366342/items/AX46XTC8/file?page=1" TEXT="ID: e7a8fbaae5d8d31eef44d0af79890148 &lt;br/&gt; RO(1): to review frameworks and game design elements that have been used as a base for Gamification  &lt;br/&gt;&lt;br/&gt;Article Title: Gamification Framework: The Contribution of User Centered Design, Social Media Applications, Gaming and Psychology Concepts and Frameworks"/>
    <node LINK="http://zotero.org/groups/2366342/items/4JKM5VGU/file?page=6" TEXT="ID: bd1b1cdd9ccf2f22adabcbbb81b53709 &lt;br/&gt; RO(1): to investigate study design used on DBGLL iin English language learning  &lt;br/&gt;&lt;br/&gt;Article Title: A scoping review of digital game-based technology on English language learning"/>
    <node LINK="http://zotero.org/groups/2366342/items/4JKM5VGU/file?page=6" TEXT="ID: 67b3bbad8373d1b367c2ca1cfcbcdeb0 &lt;br/&gt; RO(3): to investigate game practices used on DBGLL iin English language learning  &lt;br/&gt;&lt;br/&gt;Article Title: A scoping review of digital game-based technology on English language learning"/>
    <node LINK="http://zotero.org/groups/2366342/items/4JKM5VGU/file?page=6" TEXT="ID: 4351f5d52b9d69ac36ae5d147a456009 &lt;br/&gt; RO(4): to investigate game outcomes used on DBGLL iin English language learning  &lt;br/&gt;&lt;br/&gt;Article Title: A scoping review of digital game-based technology on English language learning"/>
    <node LINK="http://zotero.org/groups/2366342/items/4JKM5VGU/file?page=6" TEXT="ID: 5369c826a1bd0a1d58e121065778bff9 &lt;br/&gt; RO(2): to investigate methodology used on DBGLL iin English language learning  &lt;br/&gt;&lt;br/&gt;Article Title: A scoping review of digital game-based technology on English language learning"/>
    <node LINK="http://zotero.org/groups/2366342/items/4JKM5VGU/file?page=6" TEXT="ID: a5ad29623f1a75118181668fb3d7578e &lt;br/&gt; RO(5): to investigate game elements used on DBGLL in English language learning  &lt;br/&gt;&lt;br/&gt;Article Title: A scoping review of digital game-based technology on English language learning"/>
    <node LINK="http://zotero.org/groups/2366342/items/TSBLY85U/file?page=2" TEXT="ID: c4fdea681035d7c548ed5347fc42d1bb &lt;br/&gt; RO(1): to highlight the advances and limitations that need to be addressed in the field of adaptive gamification in education  &lt;br/&gt;&lt;br/&gt;Article Title: Adaptive Gamification in Education: A Literature Review of Current Trends and Developments"/>
  </node>
</map>
