<?xml version="1.0" encoding="UTF-8"?>
<map version="1.1.0">
  <node TEXT="Without classification">
    <node LINK="http://zotero.org/groups/2366342/items/EAWY3579/file?page=2" TEXT="Key: JNRX3YE3 &lt;br/&gt;&lt;br/&gt;Review type: SLR (mapping) (by the authors); Types of selected studies: empirical studies &lt;br/&gt;&lt;br/&gt;Title: Gamification in e-Govemment: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/MV3ESRRI/file?page=2" TEXT="Key: 7M2RXEDT &lt;br/&gt;&lt;br/&gt;Review type: literature review (mapping) (by the authors); Types of selected studies: empirical studies &lt;br/&gt;&lt;br/&gt;Title: Problem based learning using gamification: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/34H9ZFI6/file?page=1" TEXT="Key: SW5VNQKY &lt;br/&gt;&lt;br/&gt;Review type: systematic literature review (narrative review) (by the authors); Types of selected studies: empirical and non-empirical studies &lt;br/&gt;&lt;br/&gt;Title: A Gamification Model for E-Learning Platforms"/>
    <node LINK="http://zotero.org/groups/2366342/items/ZRJZK6MC/file?page=3" TEXT="Key: DMU5DZ9P &lt;br/&gt;&lt;br/&gt;Review type: systematic literature review (mapping review) (by the authors); Types of selected studies: empirical and non-empirical &lt;br/&gt;&lt;br/&gt;Title: A Review of Gamification for Learning Programming Fundamental"/>
    <node LINK="http://zotero.org/groups/2366342/items/4JKM5VGU/file?page=6" TEXT="Key: QS7KQ5N5 &lt;br/&gt;&lt;br/&gt;Review type: scoping review (by the authors); Types of selected studies: empirical studies &lt;br/&gt;&lt;br/&gt;Title: A scoping review of digital game-based technology on English language learning"/>
    <node LINK="http://zotero.org/groups/2366342/items/SYLN3YZV/file?page=1" TEXT="Key: AP894C4A &lt;br/&gt;&lt;br/&gt;Review type: Systematic Literature Review (mapping) (by the authors); Types of selected studies: empirical and non-empirical studies &lt;br/&gt;&lt;br/&gt;Title: A systematic literature review on adaptive gamification: Components, methods, and frameworks"/>
    <node LINK="http://zotero.org/groups/2366342/items/CFNJMTG7/file?page=NA" TEXT="Key: R32D2JYR &lt;br/&gt;&lt;br/&gt;Review type:  (by the authors); Types of selected studies: empirical studies &lt;br/&gt;&lt;br/&gt;Title: A systematic mapping study on gamification applied to e-marketing"/>
    <node LINK="http://zotero.org/groups/2366342/items/TSBLY85U/file?page=1" TEXT="Key: YRSQ3TXK &lt;br/&gt;&lt;br/&gt;Review type: literature review (mapping) (by the authors); Types of selected studies: non-empirical (apps) and empirical studies &lt;br/&gt;&lt;br/&gt;Title: Adaptive Gamification in Education: A Literature Review of Current Trends and Developments"/>
    <node LINK="http://zotero.org/groups/2366342/items/TMSX55QH/file?page=14" TEXT="Key: 2TQEGCTQ &lt;br/&gt;&lt;br/&gt;Review type: literature review (scoping review) (by the authors); Types of selected studies: non-empirical and empirical studies &lt;br/&gt;&lt;br/&gt;Title: Approaching Sustainability Learning Via Digital Serious Games"/>
    <node LINK="http://zotero.org/groups/2366342/items/BLJXTZCY/file?page=2" TEXT="Key: DP9LC2N7 &lt;br/&gt;&lt;br/&gt;Review type: systematic review (mapping) (by the authors); Types of selected studies: empirical studies &lt;br/&gt;&lt;br/&gt;Title: Designing Gamified Interventions for Autism Spectrum Disorder: A Systematic Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/FXL69DGN/file?page=1" TEXT="Key: 6INXC8HH &lt;br/&gt;&lt;br/&gt;Review type: systematic mapping (by the authors); Types of selected studies: empirical and non-empirical studies &lt;br/&gt;&lt;br/&gt;Title: Engaging MOOC through gamification: Systematic mapping review"/>
    <node LINK="http://zotero.org/groups/2366342/items/ADG26DDQ/file?page=1" TEXT="Key: EKUQ6GZ6 &lt;br/&gt;&lt;br/&gt;Review type: systematic review (narrative review) (by the authors); Types of selected studies: empirical and non-empirical studies &lt;br/&gt;&lt;br/&gt;Title: Enterprise gamification systems and employment legislation: a systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/PHKXE7KX/file?page=1" TEXT="Key: RL9YEDGQ &lt;br/&gt;&lt;br/&gt;Review type: literature mapping (by the authors); Types of selected studies: empirical and non-empirical studies with more than 60 citations &lt;br/&gt;&lt;br/&gt;Title: Gamification as a strategy to improve students’ motivation and engagement in educational environments at engineering courses: bibliographic"/>
    <node LINK="http://zotero.org/groups/2366342/items/AX46XTC8/file?page=2" TEXT="Key: Y2I3R58N &lt;br/&gt;&lt;br/&gt;Review type: review of the literature (narrative) (by the authors); Types of selected studies: empirical and non-empirical studies &lt;br/&gt;&lt;br/&gt;Title: Gamification Framework: The Contribution of User Centered Design, Social Media Applications, Gaming and Psychology Concepts and Frameworks"/>
    <node LINK="http://zotero.org/groups/2366342/items/UDM6MNDX/file?page=1" TEXT="Key: D2DXYT2K &lt;br/&gt;&lt;br/&gt;Review type: systematic review (mapping) (by the authors); Types of selected studies: empirical and non-empirical studies &lt;br/&gt;&lt;br/&gt;Title: Gamification in apps and technologies for improving mental health and well-being: Systematic review"/>
    <node LINK="http://zotero.org/groups/2366342/items/24JK4VEG/file?page=2" TEXT="Key: MPMB45G9 &lt;br/&gt;&lt;br/&gt;Review type: mapping review (by the authors); Types of selected studies: empirical and non-empirical studies &lt;br/&gt;&lt;br/&gt;Title: Gamification in CPR - A Review of Game Dynamics and Mechanics"/>
    <node LINK="http://zotero.org/groups/2366342/items/H5KSNXDS/file?page=2" TEXT="Key: SRBEUBEH &lt;br/&gt;&lt;br/&gt;Review type: systematic mapping (by the authors); Types of selected studies: empirical and non-empirical (reviews) studies &lt;br/&gt;&lt;br/&gt;Title: Gamification in IoT application: A systematic mapping study"/>
    <node LINK="http://zotero.org/groups/2366342/items/U78FKG67/file?page=2" TEXT="Key: SQDTS6KC &lt;br/&gt;&lt;br/&gt;Review type:  mapping of the literature (by the authors); Types of selected studies: empirical and non-empirical studies &lt;br/&gt;&lt;br/&gt;Title: Gamification in management education - A literature mapping"/>
    <node LINK="http://zotero.org/groups/2366342/items/SSENW62L/file?page=4" TEXT="Key: J4BHC26J &lt;br/&gt;&lt;br/&gt;Review type: systematic review (narrative review) (by the authors); Types of selected studies: empirical and non-empirical studies &lt;br/&gt;&lt;br/&gt;Title: Gamification in Management: analysis and research directions"/>
    <node LINK="http://zotero.org/groups/2366342/items/ERBZ46ZZ/file?page=1" TEXT="Key: H696TSSJ &lt;br/&gt;&lt;br/&gt;Review type: systematic mapping (by the authors); Types of selected studies: empirical and non-empirical studies &lt;br/&gt;&lt;br/&gt;Title: Main gamification concepts: A systematic mapping study"/>
    <node LINK="http://zotero.org/groups/2366342/items/ZHZEUC5A/file?page=1" TEXT="Key: GV7WT7H5 &lt;br/&gt;&lt;br/&gt;Review type: literature review (narrative) (by the authors); Types of selected studies: empirical and non-empirical studies &lt;br/&gt;&lt;br/&gt;Title: Review of benefit using gamification element for countryside tourism"/>
    <node LINK="http://zotero.org/groups/2366342/items/2IH7Y8RH/file?page=1" TEXT="Key: PA9ZB2CW &lt;br/&gt;&lt;br/&gt;Review type: Systematic Literature Review (by the authors); Types of selected studies: empirical and non-empirical &lt;br/&gt;&lt;br/&gt;Title: Serious game, gamified applications, educational software: A comparative study"/>
    <node LINK="http://zotero.org/groups/2366342/items/4TDM3GFC/file?page=2" TEXT="Key: XZR3LKIN &lt;br/&gt;&lt;br/&gt;Review type: review of the literature (narrative) (by the authors); Types of selected studies: empirical studies &lt;br/&gt;&lt;br/&gt;Title: Serious Games and Gamification in the Corporate Training Environment: a Literature Review"/>
    <node LINK="http://zotero.org/groups/2366342/items/KBI5Y6SI/file?page=" TEXT="Key: HTG2D2EL &lt;br/&gt;&lt;br/&gt;Review type:  (by the authors); Types of selected studies:  &lt;br/&gt;&lt;br/&gt;Title: Serious gaming as a means of facilitating truly smart cities: a narrative review"/>
    <node LINK="http://zotero.org/groups/2366342/items/CYHRUKLX/file?page=" TEXT="Key: 7GZALWCA &lt;br/&gt;&lt;br/&gt;Review type:  (by the authors); Types of selected studies:  &lt;br/&gt;&lt;br/&gt;Title: The effects of gamification in online learning environments: A systematic literature review"/>
    <node LINK="http://zotero.org/groups/2366342/items/QGNF2RLP/file?page=1" TEXT="Key: Z25JLEAQ &lt;br/&gt;&lt;br/&gt;Review type: meta-analysis (by the authors); Types of selected studies: empirical studies &lt;br/&gt;&lt;br/&gt;Title: The effects of gamification on students’ academic achievement: a meta-analysis study"/>
    <node LINK="http://zotero.org/groups/2366342/items/RY2DM4V4/file?page=3" TEXT="Key: 8NTDBRIF &lt;br/&gt;&lt;br/&gt;Review type: review (narrative) (by the authors); Types of selected studies: empirical and non-empirical studies &lt;br/&gt;&lt;br/&gt;Title: The Hero's Journey to Innovation: Gamification in Enterprise Systems"/>
    <node LINK="http://zotero.org/groups/2366342/items/22XCUTKU/file?page=1" TEXT="Key: 9BNF29KS &lt;br/&gt;&lt;br/&gt;Review type: systematic review (by the authors); Types of selected studies: empirical studied &lt;br/&gt;&lt;br/&gt;Title: The Role of Gamification Techniques in Promoting Student Learning: A Review and Synthesis"/>
    <node LINK="http://zotero.org/groups/2366342/items/IHLIL5I5/file?page=" TEXT="Key: 8L29NV9E &lt;br/&gt;&lt;br/&gt;Review type:  (by the authors); Types of selected studies:  &lt;br/&gt;&lt;br/&gt;Title: Using gamification to support learning English as a second language: a systematic review"/>
  </node>
</map>
